### ISSUE TITLE
Error during update cf-mysql-broker_z1/0;  in cf-mysql-release-v25

### ISSUE THREAD

**Issue by ramkumar-kandakumar** [cloudfoundry/cf-mysql-release#107]
**Error** in logged in "/var/vcap/sys/log/quota-enforcer/quota_enforcer.stdout.log" as below,

{"timestamp":"1465443979.907010078","source":"Quota Enforcer","message":"Quota Enforcer.Enforcing Failed: Finding violators: Error executing 'quota violator'.All: Error 1146: Table 'mysql_broker.service_instances' doesn't exist","log_level":1,"data":{}}

**deployment-manifest.yml**
_attached_ [cf-mysql.txt](https://github.com/cloudfoundry/cf-mysql-release/files/306095/cf-mysql.txt)

**Evironment**
-aws
-microbosh

**cf-mysql-release-version**
v25

**Comment by mfine30** [comment]
Hi @ramkumar-kandhakumar-cognizant-com,

It seems like the database that the `mysql_broker` created inside of the cluster is not available. Do you have any other logs from the `cf-mysql-broker_z1` job? In particular, logs related to the actual service-broker itself would be helpful. If you could provide those we can help you out more.

Thanks,
Morgan 
CF Core Services

**Comment by ramkumar-kandhakumar-cognizant-com** [comment]
Hi Morgan,
Below is the error in "/var/vcap/sys/log/cf-mysql-broker/db_migrate.combined.log"
**Errno::ETIMEDOUT: Connection timed out - connect(2) for "api.cognizantone.org" port 443**
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-e0806168cd4cb3cdbdf59b6c2679a05d8b6c85de/app/models/cloud_controller_http_client.rb:14:in `get'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-e0806168cd4cb3cdbdf59b6c2679a05d8b6c85de/lib/configuration.rb:28:in `cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-e0806168cd4cb3cdbdf59b6c2679a05d8b6c85de/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-e0806168cd4cb3cdbdf59b6c2679a05d8b6c85de/config/initializers/omniauth.rb:10:in `block in <top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:6:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `inject'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/stack.rb:118:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/engine.rb:495:in `app'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.2.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/vcap/data/packages/cf-mysql-broker/47cdbff74dadd949abd599bbd259fe7a53bbd68f.1-e0806168cd4cb3cdbdf59b6c2679a05d8b6c85de/config/environment.rb:5:in `<top (required)>'

Thanks & Regards
Ram Kumar

**Comment by mfine30** [comment]
Hey,

Sorry for the delay. Looking through the logs, it looks like your Cloud Foundry cloud controller was not available while bosh was deploying the mysql broker. During the broker job startup, it attempts to connect to the cloud controller. In this situation, that was happening as migrations were being run, which is why the quota enforcer was unable to access that table.

We suggest you try to redeploy after the cloud controller is accessible.

Best,
Morgan & Tammer
