### ISSUE TITLE
Example generated manifest is missing properties/jobs

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/cf-mysql-release#115]
1. Check out cf-mysql-release
1. Note that branch is set to `develop`
1. Go about instructions for [deploying on aws](https://github.com/cloudfoundry/cf-mysql-release/blame/develop/README.md#L299-L361)
1. See error:
   ```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 253
  Started preparing deployment > Preparing deployment. Failed: Can't find job 'rejoin-unsafe' (00:00:01)

Error 190011: Can't find job 'rejoin-unsafe'
    ```
1. Switch branch to `master` per @aaronshurley (on slack)

    > Aaron Hurley [9:24 AM]  
    > @jdeklerk: which branch are you on for manifest generation? `master` should work,  or you can git checkout that tag

1. Attempt to regenerate deployment manifest [per the docs](https://github.com/cloudfoundry/cf-mysql-release/blame/develop/README.md#L329-L353)
1. See new error about unresolved nodes:

    ```
/usr/bin/env bash /Users/pivotal/Library/Preferences/IntelliJIdea2016.1/scratches/scratch.sh
2016/06/29 12:06:51 error generating manifest: unresolved nodes:
	(( property_overrides.mysql.bootstrap_endpoint ))	in /Users/pivotal/workspace/jean-temp/cf-mysql-release/manifest-generation/cf-mysql-template.yml	properties.cf_mysql.mysql.bootstrap_endpoint	()
2016/06/29 12:06:51 error parsing stub [/tmp/mysql_manifest.yNDCM/mysql-config.yml]: Expected document start at line 0, column 0

    ```

**Comment by jadekler** [comment]
Turns out `master` branch has the correct files, so doing a `git checkout master` before going through copying everything works fine. Might be worth a note in the README? Either way this seems to be a non-issue.

**Comment by menicosia** [comment]
@jadekler -- what version of `spiff` do you have? Current develop branch requires 1.0.7. You can't see that yet coz the release notes haven't been published yet.

Your point that the `README.md` should tell you which version of spiff is required is well taken.

**Comment by jadekler** [comment]
Aha, thanks @menicosia. We have 1.0.6

**Comment by jdspecht** [comment]
Hello,

I have the correct version of spiff as per the README (1.0.7). I have checked out branch master. I am still getting the same error as @jadekler when attempting to generate the deployment manifest:

```
$ ./scripts/generate-deployment-manifest -c ~/configs/cf-stub.yml -p ~/configs/property-overrides.yml -i ~/configs/iaas-settings.yml
2016/08/15 19:14:51 error generating manifest: unresolved nodes:
	(( property_overrides.mysql.bootstrap_endpoint ))	in /home/ubuntu/1/cf-mysql-release/manifest-generation/cf-mysql-template.yml	properties.cf_mysql.mysql.bootstrap_endpoint	()
2016/08/15 19:14:51 error parsing stub [/tmp/mysql_manifest.3Sd1k/mysql-config.yml]: Expected document start at line 0, column 0
```
