### ISSUE TITLE
cf-mysql-cluster-health-logger Submodule Added with SSH URL

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/cf-mysql-release#117]
It seems like the cf-mysql-cluster-health-logger submodule was recently added to the releases/v26 branch. Would it be possible to switch it to point to the https version so Concourse can check that branch out without needing SSH keys uploaded to github?

https://github.com/cloudfoundry/cf-mysql-release/blob/releases/v26/.gitmodules#L135

Thanks!

**Comment by chendrix** [comment]
for sure.

**Comment by davewalter** [comment]
That was fast! Thanks.

**Comment by chendrix** [comment]
No problem. I will let you know once it's through CI to make sure I didn't suddenly break things.

**Comment by robdimsdale** [comment]
This should now be available on releases/v26 branch
