### ISSUE TITLE
cf-mysql-broker_z1/0 is not running after update. Mysql2::Error: Can't connect to MySQL server

### ISSUE THREAD

**Issue by slowbackspace** [cloudfoundry/cf-mysql-release#118]
Hi, I have been struggling with this for 3 days. Deployment to openstack fails with
```
Started updating job cf-mysql-broker_z1 > cf-mysql-broker_z1/0 (1264fbbb-79c0-40c3-a79f-d5a3115b6263) (canary). Failed: 'cf-mysql-broker_z1/0 (1264fbbb-79c0-40c3-a79f-d5a3115b6263)' is not running after update. Review logs for failed jobs: cf-mysql-broker, quota-enforcer (00:11:06)

Error 400007: 'cf-mysql-broker_z1/0 (1264fbbb-79c0-40c3-a79f-d5a3115b6263)' is not running after update. Review logs for failed jobs: cf-mysql-broker, quota-enforcer
```

db_migrate.combined.log from cf-mysql-broker_z1:
```
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"mysql_broker", "pool"=>5, "connect_timeout"=>20, "read_timeout"=>20, "reconnect"=>true, "host"=>"192.168.2.101", "port"=>3306, "username"=>"root", "password"=>"REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP"}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
rake aborted!
Mysql2::Error: Can't connect to MySQL server on '192.168.2.101' (107)
```

/var/vcap/sys/log/proxy/switchboard.combined.log from proxy_z1
```
{"timestamp":"1469801665.516019344","source":"/var/vcap/packages/switchboard/bin/switchboard","message":"/var/vcap/packages/switchboard/bin/switchboard.lock.retrying-acquiring-lock","log_level":1,"data":{"key":"v1/locks/REPLACE_WITH_YOUR_DESIRED_NAME_lock","session":"1","value":""}}
{"timestamp":"1469801665.516563654","source":"/var/vcap/packages/switchboard/bin/switchboard","message":"/var/vcap/packages/switchboard/bin/switchboard.lock.failed-to-recreate-session","log_level":2,"data":{"error":"Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused","key":"v1/locks/REPLACE_WITH_YOUR_DESIRED_NAME_lock","session":"1","value":""}}

```
bosh vms output:
```
+-------------------------------------------------------------+----------+-----+--------------------+---------------+
| VM                                                          | State    | AZ  | VM Type            | IPs           |
+-------------------------------------------------------------+----------+-----+--------------------+---------------+
| cf-mysql-broker_z1/0 (048e1a63-ef93-4411-9131-1464091ec456) | starting | n/a | cf-mysql-broker_z1 | 192.168.2.81  |
| mysql_z1/0 (46ad6018-8084-4398-ab8c-9da93bca9a11)           | running  | n/a | mysql_z1           | 192.168.2.100 |
| proxy_z1/0 (b1b0b4bc-7d7e-45b6-9b44-5d6473d9911c)           | running  | n/a | proxy_z1           | 192.168.2.101 |
+-------------------------------------------------------------+----------+-----+--------------------+---------------+
```

Deployment manifest was generated using
`scripts/generate-deployment-manifest -c ../mysql-cf-stub.yml -p ../mysql-property-overrides.yml  -n manifest-generation/examples/minimal/instance-count-overrides.yml -i ../mysql-iaas-settings.yml > ../mysql-cf-deployment.yml`

[mysql-iaas-settings.yml](https://gist.github.com/slowbackspace/6f920f8c50d7aae18d9920cfd88e615f)
[mysql-property-overrides.yml](https://gist.github.com/slowbackspace/7ded52687b73ae64fc9f82470b3e65bb)
[mysql-cf-stub.yml]
(https://gist.github.com/slowbackspace/a27fd9bbf4a966f65a5beee9a6121545)
and generated manifest
[mysql-cf-deployment.yml](https://gist.github.com/slowbackspace/501278e8bb3bcd9fb6a2390c1d6ff972)

If I change properties.cf_mysql.host from 192.168.2.101 (proxy_z1's IP) to 192.168.2.100 (mysql_z1's IP) then deployment is successful, but cf bind-service provides access to MySQL via 192.168.2.100 address. If I am not mistaken, this means that the proxy is not being used at all so not exactly what I want.
What am I missing?

**Comment by robdimsdale** [comment]
@slowbackspace what version of cf-mysql-release are you using? v27? Building from master branch?

It looks like switchboard is trying to communicate with consul, but consul is not running. From your manifest it looks like you set `consul_enabled: false` 

On the face of it this is confusing, because it looks like if this setting is false we should not be configuring consul at all, so it's not clear why switchboard is trying to communicate with it: https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/proxy/templates/switchboard.yml.erb#L29-L32

**Comment by slowbackspace** [comment]
Currently I am on develop branch (Your branch is up-to-date with 'origin/develop'), but I think I had the same problem with release-candidate.
Following your hint I noticed that in file /var/vcap/jobs/proxy/config/switchboard.yml on proxy_z1 are following lines:
```
"ConsulCluster": http://127.0.0.1:8500
"ConsulServiceName": REPLACE_WITH_YOUR_DESIRED_NAME
```
So I deleted them, run monit restart all and bosh recreate cf-mysql-broker_z1 and it finished successfully.

I can try it again for the fun again with the master branch. What are exact steps for switching to master? git checkout master, run update script, generate manifest, bosh create/upload release and bosh deploy?

**Comment by chendrix** [comment]
The `master` branch doesn't yet have consul, so that would work fine, except you're correct - there is a missing submodule (candiedyaml). We are aware of this, and it will be fixed when we create the next final release and `master` is updated. For now you can `bosh upload release releases/cf-mysql-release-26.yml` instead of creating your own and uploading it.

You can also instead use the feature of uploading a remote release, since all of our releases are up on bosh.io

```
bosh upload release https://bosh.io/d/github.com/cloudfoundry/cf-mysql-release?v=26
```

**Comment by slowbackspace** [comment]
Great, thanks. One problem still remains. It seems that I can't unbind service instance.
Job is queued but that's it, nothing happens afterwards. Where should I look for more debug info?
`REQUEST: [2016-08-02T08:55:31Z]
DELETE /v2/service_bindings/802a9885-176c-41df-86d1-9472d769ff25?async=true HTTP/1.1
Host: api.domain
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.20.0+25b1961 / linux



RESPONSE: [2016-08-02T08:55:31Z]
HTTP/1.1 202 Accepted
Content-Length: 270
Content-Type: application/json;charset=utf-8
Date: Tue, 02 Aug 2016 09:24:39 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 7511a597-daa3-49b7-7570-04290ee6118a
X-Vcap-Request-Id: 7511a597-daa3-49b7-7570-04290ee6118a::62a56187-7dc8-4f1c-b67b-0c330a4fd532

{
  "metadata": {
    "guid": "292cf7b6-023c-4c76-9e1c-58e2f055b7aa",
    "created_at": "2016-08-02T09:24:39Z",
    "url": "/v2/jobs/292cf7b6-023c-4c76-9e1c-58e2f055b7aa"
  },
  "entity": {
    "guid": "292cf7b6-023c-4c76-9e1c-58e2f055b7aa",
    "status": "queued"
  }
}

REQUEST: [2016-08-02T08:55:31Z]
GET /v2/jobs/292cf7b6-023c-4c76-9e1c-58e2f055b7aa HTTP/1.1
Host: api.domain
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.20.0+25b1961 / linux



RESPONSE: [2016-08-02T08:55:31Z]
HTTP/1.1 200 OK
Content-Length: 270
Content-Type: application/json;charset=utf-8
Date: Tue, 02 Aug 2016 09:24:39 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 5dc9392c-a111-4324-4871-5270ad922541
X-Vcap-Request-Id: 5dc9392c-a111-4324-4871-5270ad922541::741526bc-b4d6-4c73-98ab-68a8d892585e

{
  "metadata": {
    "guid": "292cf7b6-023c-4c76-9e1c-58e2f055b7aa",
    "created_at": "2016-08-02T09:24:39Z",
    "url": "/v2/jobs/292cf7b6-023c-4c76-9e1c-58e2f055b7aa"
  },
  "entity": {
    "guid": "292cf7b6-023c-4c76-9e1c-58e2f055b7aa",
    "status": "queued"
  }
}`

**Comment by slowbackspace** [comment]
I solved the above issue by adding following lines to cf manifest.
```
  - name: cloud_controller_worker
    release: cf
  - name: cloud_controller_clock
    release: cf
```
