### ISSUE TITLE
Remove custom syslog support in favor of integration with Syslog Release

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-mysql-release#123]
Instead of managing your own syslog perhaps you would consider working with the team that manages https://github.com/cloudfoundry/syslog-release

Might take some coordination though:
- I know cf-mysql needs to add some custom imfile rules perhaps these rules could be added to the syslog chain prior to the where the syslog-release runs.
- syslog-release starts as a pre-start script now.  Perhaps syslog-release could reload post-start as well to ensure job specific syslog config gets loaded?

Thoughts?

**Comment by menicosia** [comment]
Thanks @youngm!

Let me look into this. I know that there are some broader efforts going on around logging; I will check with the stakeholders.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment]
Hi @youngm,

We've been looking at this story, and decided to put in an Explore story ahead of it to make sure we know what we're doing when we go to make this happen. You can follow that story, if you like, at [#131474577](https://www.pivotaltracker.com/story/show/131474577)

**Comment by zankich** [comment]
This work has been completed in [v36.10.0](https://github.com/cloudfoundry/cf-mysql-release/releases/tag/v36.10.0).
