### ISSUE TITLE
Route-registrar should advertize the host provided in spec

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry/cf-mysql-release#126]
We would like the host that the [broker advertizes](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/cf-mysql-broker/templates/registrar_settings.yml.erb#L24) via nats to be configurable via the spec.

Our issue is that, as part of our ci pipeline we are bringing up cf-mysql in bosh-lite and want to register it with a cf running in another bosh-lite so we need to advertize the external_ip of the bosh-lite it is running on instead of the internal ip for this to work

**Comment by mfine30** [comment]
@bodymindarts this seems related to #127. I'm going to close this so we only have one spot for the conversation to take place.

Thanks!
