### ISSUE TITLE
Recommendations for backup - innobackupex vs xtrabackup

### ISSUE THREAD

**Issue by penrod** [cloudfoundry/cf-mysql-release#128]
Looking for some help on backing up our cf-mysql-release. Bear with me as I'm not a real db admin but I sometimes play as one during the day. 

Previous to running cf-msyql-release, we utilized percona. My backup script called innobackupex to pull a backup. When I attempt to use innobackupex on the cf-mysql-release, I get this error:
...
160921 21:22:42  innobackupex: Connecting to MySQL server with DSN 'dbi:mysql:;mysql_read_default_group=xtrabackup' (using password: NO).
innobackupex: got a fatal error with the following stacktrace: at ./innobackupex line 2998.
	main::mysql_connect('abort_on_error', 1) called at ./innobackupex line 1539
innobackupex: Error: Failed to connect to MySQL server as DBD::mysql module is not installed at ./innobackupex line 2998.
...
Searching around a bit comes up with the most likely cause being a missing library perl-DBD-MySQL.

I can run the xtrabackup command  and should be able to do what I need with it, but I've used innobackupex successfully for some time and I'm curious why its not functional with the cf-mysql-release(v27).

**Comment by jpalermo** [comment]
Hi @penrod 

You'll need to export PERL5LIB to point to the correct place. With the most recent version, you should be able to export the following on the mysql data node:
`export PERL5LIB=$PERL5LIB:/var/vcap/packages/xtrabackup/lib/perl/5.18.2`

You'll also need xtrabackup on the path, so you may need this export:
`export PATH=$PATH:/var/vcap/packages/xtrabackup/bin/`

If that doesn't work for you, let us know what release version of cf-mysql you are using, and what command you are running.

**Comment by penrod** [comment]
Awesome. I was adding the xtrabackup bin to the path but could not find any evidence of innobackupex, so I spaced adding the perl. Thank for getting me on track again.
