### ISSUE TITLE
Bug Report: Load Balancing Issue in mysql (for vms proxy_z1 & proxy_z2)

### ISSUE THREAD

**Issue by stefy-varghese** [cloudfoundry/cf-mysql-release#140]
hello team,
Facing an issue of improper load balancing in mysql,
tried with 2 conditions:
1) **When we stop proxy_z2 vm, the load is handled by proxy_z1 vm** . Hence an app can be pushed , a service instance can be created , also the app can be bound with the service instance created and it can be re staged successfully. 
![proxyz2-stopped](https://cloud.githubusercontent.com/assets/24524607/21128783/a07ca278-c123-11e6-869e-a2f91fa445a1.png)
![proxyz2-stopped-output](https://cloud.githubusercontent.com/assets/24524607/21128791/a94761b8-c123-11e6-9159-a5c2732b4e93.png)

2) **When we stop proxy_z1 vm, the load is not being handled by proxy_z2 vm** .  We are able to push an app but we are unable to create service instance and the further steps to run an app.
![proxyz1-stopped](https://cloud.githubusercontent.com/assets/24524607/21128852/1d5ba488-c124-11e6-903e-952d16e38097.png)
![proxyz1-stoppederr](https://cloud.githubusercontent.com/assets/24524607/21128977/f0810614-c124-11e6-8e05-7c7eb16e34a8.png)

When we check the environment variable with the command   **cf env app_name**  by default it take the ip of proxy_z1 vm in both the conditions.
Could anyone please look into this issue and revert.??

**Comment by jpalermo** [comment]
The bosh manifest property `cf_mysql.host` for the `cf-mysql-broker` job is what the service broker gives to the apps as the host when they provision a service instance.

If you are using the scripting for generating a deployment manifest, and you fail to specify a `property_overrides.host` property, the manifest generation will use the IP address of proxy_z1 as a default.

The cf-mysql release does not come with a load balancer. You need to configure a load balancer and point it at both of your proxy instances. You can then use the load balancer address as the value of `propery_overrides.host` if using the included manifest generation scripts, or `cf_mysql.host` if you are building the bosh manifest yourself.

After deploying this change, you'll need to rebind the service instances to the apps so they get the updated host configuration.

**Comment by stefy-varghese** [comment]
We configured a load balancer and pointed it to both the proxy instances. But we are facing the following issue, when checked in the logs.
![quota](https://cloud.githubusercontent.com/assets/24524607/21217931/af3fb68a-c2d4-11e6-897b-61923e20d3b4.png)

We have added the following changes in our manifest for configuring the load balancer:

- We have added a new job haproxy-mysql which contains 2 ips of proxy vms, added the cf-haproxy release for the same. Also for host we have assigned the ip of haproxy and consul is enabled to true.
![job-haproxy](https://cloud.githubusercontent.com/assets/24524607/21218022/eab9b01c-c2d4-11e6-9104-dea549a09827.png)
![host](https://cloud.githubusercontent.com/assets/24524607/21218062/19b409da-c2d5-11e6-8677-d7b439a28448.png)
![consul](https://cloud.githubusercontent.com/assets/24524607/21218064/1c4539d0-c2d5-11e6-8200-4f12d15c5a63.png)
![releases](https://cloud.githubusercontent.com/assets/24524607/21218069/2368675a-c2d5-11e6-9703-69919349f01e.png)

**Comment by jpalermo** [comment]
Perhaps we should step back for a second and figure out what you are trying to accomplish. Are you trying to bring up a mysql cluster that is highly available?

If you are, adding cf-haproxy will not help. The haproxy node is now a single point of failure and anytime you need to update it (with a stemcell update or anything) the cluster will be unavailable. This is the reason we don't include a load balancer in the cf-mysql release. There is currently no bosh deployable way to create a HA load balancer. A proper load balancer has a single hostname that is balanced between multiple nodes, and currently there is not an IAAS agnostic way of doing this.

If you are not trying to make a highly available cluster, you can simply scale your proxy nodes down to 1 and you should have the same or better availability you'd get with a bosh deployed haproxy release involved.

**Comment by robdimsdale** [comment]
We'll close this now as there's been no response in a week. Please feel free to reopen with further info.
