### ISSUE TITLE
Update socat version?

### ISSUE THREAD

**Issue by manno** [cloudfoundry/cf-mysql-release#143]
I'm trying to compile cf-mysql-release with a custom openSUSE based stemcell. However the kernel  is too new and socat 1.7.2.4  won't compile.
I understand this is not supported, but could you bump socat to 1.7.3.0?

**Comment by menicosia** [comment]
Hi @manno,

This isn't something we're likely to be able to focus on in the near future, but if there were any chance you could supply a PR, I'm certain we could find time to run it through the pipeline.

Is there any chance you might be able to do this?

--

Marco Nicosia
Product Manager

**Comment by manno** [comment]
Hi @menicosia,

Sure, I'll change the version numbers in the packaging and test a dev release. However I can't add blobs to the store. So I just give the new socat URL in the PR text?

**Comment by menicosia** [comment]
Yes, that sounds great. We'll be happy to meet you halfway on this. We'll accept your PR to the blobs yml, and we'll use that URL to add the blob. What we expect from you, however, is to additionally make sure that this works - ie deploy and compile, and make sure that the smoke-tests errand works.

We'd really appreciate it if you'd be able to run the official stemcell through smoke-tests as well. Is that possible, perhaps through a bosh-lite?

--

Marco Nicosia
Product Manager

**Comment by robdimsdale** [comment]
To expand further, tracking down the "right" version of a blob can be particularly challenging and time-consuming, as can validating the compilation succeeds. It's hard for us to justify this effort for an unsupported stemcell.

We're happy to merge an update to this blob if you can provide us an exact URL to a tarball of the source, you make the necessary changes to the packaging scripts, and you've validated it on your custom stemcell as well as the offically-supported ubuntu stemcell.

**Comment by manno** [comment]
Great, this made it into our sprint, so I should be able to test and deploy my branch next week with both stemcells.

**Comment by robdimsdale** [comment]
Sounds good - thanks.
