### ISSUE TITLE
Can't deploy on bosh-lite because job deregister-and-purge-instances can't be found

### ISSUE THREAD

**Issue by manno** [cloudfoundry/cf-mysql-release#147]
I generated the manifest for bosh-lite with `scripts/generate-bosh-lite-manifest`. However `bosh deploy` fails with:

```
Deploying
---------

Director task 16
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Failed: Can't find job 'deregister-and-purge-instances' (00:00:01)

Error 190011: Can't find job 'deregister-and-purge-instances'

Task 16 error
```

**Comment by robdimsdale** [comment]
We recently renamed this job in the `develop` branch but haven't created a final release yet so the changes aren't on `master`, so if you're using manifest generation from the `develop` branch that will require that you create a release from the `develop` branch. If you want to use a final release, please checkout the `master` branch and run the script from there.

**Comment by manno** [comment]
Thanks, creating a dev release from the develop branch fixes my problem.
