### ISSUE TITLE
Unused proxy ip property

### ISSUE THREAD

**Issue by madamkiwi** [cloudfoundry/cf-mysql-release#156]
Hi,

In working on a BOSH link story, we discovered that this property doesn't seem to be used anymore: https://github.com/cloudfoundry/cf-mysql-release/blob/v34/jobs/proxy/spec#L92-L93

If in case we are mistaken, please let us know.

@madamkiwi & @kkallday

**Comment by menicosia** [comment]
@madamkiwi @kkallday

We'll look into this and get back to you, thanks!

**Comment by utricularian** [comment]
@madamkiwi @kkallday

The property is still used if proxy link is not present, like the following example,
https://github.com/cloudfoundry/cf-mysql-release/blob/166f26c38aceafd3d3aac0bfde760b66b2817d92/jobs/smoke-tests/templates/config.yml.erb#L18

**Comment by kkallday** [comment]
👍🏿
