### ISSUE TITLE
Manifest Generation Broken

### ISSUE THREAD

**Issue by apeschel** [cloudfoundry/cf-mysql-release#160]
Attempting to use the `generate-deployment-manifest` script results in an error at the following two lines:

https://github.com/cloudfoundry/cf-mysql-release/blob/develop/manifest-generation/cf-mysql-template.yml#L47-L48

These keys come from the following templates:

https://github.com/cloudfoundry/cf-mysql-release/blob/develop/manifest-generation/misc-templates/config-from-cf.yml#L16-L18

https://github.com/cloudfoundry/cf-mysql-release/blob/develop/manifest-generation/misc-templates/config-from-cf-internal.yml#L16-L18

Both of which just use the value from the base `cf-manifest.yml`.

According to the [documentation](https://github.com/cloudfoundry/uaa/blob/3.16.0/docs/Sysadmin-Guide.rst) for UAA, the format for `uaa.scim.users` should be as follows:

```
scim:
   users:
      - sre@vmware.com|apassword|scim.write,scim.read,openid
```

And it has been as such for as far back as the UAA repo has stable releases.

It looks like the issue was introduced in this commit: https://github.com/cloudfoundry/cf-mysql-release/commit/9491ff647f54fa0753ce08469789330a83739433

This commit uses an undocumented and non-standard format for `uaa.scim.users`, which causes breakage when used with a manifest containing the documented standard format.

**Comment by fhanik** [comment]
@apeschel 
Here is the property documented for uaa-release (cf manifests)
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L441-L469

what error are you experiencing? and what version of the UAA (or uaa-release) are you using?

**Comment by apeschel** [comment]
@fhanik Thanks for the extremely quick response, I've been trying to get as much information together as I can before replying.

I was trying to get cf-mysql-release working with the out of the box Azure template referenced here:

https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/via-arm-templates/deploy-bosh-via-arm-templates.md

It appears that this is the repository with the actual template that gets deployed:

https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup

This template comes with a couple of reference `cf-manifests.yml` files, I chose the (`single-vm-cf.yml`)[https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml] manifest as a reference.

Using this template results in the following releases being deployed:

```
+-------------------+-----------+-------------+
| Name              | Versions  | Commit Hash |
+-------------------+-----------+-------------+
| cf                | 238*      | 67fa6abf+   |
| cflinuxfs2-rootfs | 1.16.0*   | fa43f35a+   |
| diego             | 0.1476.0* | 23caa9d3    |
| garden-linux      | 0.338.0*  | 38e53b4a    |
+-------------------+-----------+-------------+
```

Looking at [`cf-release` version `238`](https://github.com/cloudfoundry/cf-release/tree/v238/src), I found it links to [cloudfoundry/uaa](https://github.com/cloudfoundry/uaa/tree/3.15.0) 3.15.0, which is where I found the documentation for `uaa.scim.users` that I linked to above.

It is entirely possible for me to update the provided `single-vm-cf-yml` manifest to use the new `uaa.scim.users` format, but there is still a lot of documentation and stubs floating around using this old format.

**Comment by apeschel** [comment]
Here are a few places I've run into the single line format:

https://github.com/cloudfoundry/uaa/blob/3.15.0/docs/Sysadmin-Guide.rst#user-bootstrapping

https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/single-vm-cf.yml#L726-L729

https://docs.cloudfoundry.org/deploying/common/deploy.html#verify

**Comment by fhanik** [comment]
Ok, this makes sense. The cf 238 has UAA 3.4.1.
Since then the UAA has implemented the "map" format for a user, and retaining the pipe delimited format for backwards compatibility. 

If possible, I'd recommend upgrading your cf deployment.

I'll leave this with the cf-mysql-release team to decide if they wish to be compatible that way back.
The UAA prefers a format of https://github.com/cloudfoundry/uaa-release/blob/8c5ccff535f9fb3b924a3d1c52f795b0f8242054/jobs/uaa/spec#L417-L445

Older versions of uaa-release had
https://github.com/cloudfoundry/uaa-release/blob/3307137ef931d1b75a58b2aa1ba8be887a165584/jobs/uaa/spec#L431-L432

Both formats currently work, but we are phasing out the pipe delimited.

**Comment by menicosia** [comment]
Hi @apeschel,

We've switched over to the new UAA SCIM format as of [v28](https://github.com/cloudfoundry/cf-mysql-release/releases/tag/v28).

I agree with @fhanik that if at all possible, it'd be best if you could upgrade your version of CF, as v238 is nearly a year old, now.

Please let me know if we can close this issue.

----
Marco Nicosia
Product Manager
