### ISSUE TITLE
Setting ulimit in pre-start doesn't have any effect in main lifecycle

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/cf-mysql-release#161]
Talking with @xoebus and @cppforlife, we learned that setting `ulimit` in `pre-start` won't have any effect in the main lifecycle of a bosh job. Currently this happens for the mysql job here:

https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/mysql/templates/pre-start-setup.erb#L49

It's possible that we don't care what the `ulimit` is during the main job execution, but that seems unlikely; what happens when the user has more than 1024 databases?

**Comment by abg** [comment]
Are you seeing a lower (or different) max open files limit for the running MySQL job compared to prestart?  The main job sets its resource limit similarly here:

https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/mysql/templates/mariadb_ctl.erb#L43

Setting ```cf_mysql.mysql.max_open_files``` during deploy seems to have the intended effect.

**Comment by robdimsdale** [comment]
Ah, thanks @abg, I was looking for a corresponding line in the main, as well as the pre-start, but I missed it. I hadn't observed this behavior in the wild - I was only looking at code. I'll close this now.
