### ISSUE TITLE
cf-mysql-broker_z1/0 is not running after update. SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by rdoerr01** [cloudfoundry/cf-mysql-release#162]
I've been pulling my hair out for 3 days on trying to get a single Service (cf-mysql) install on my CF Release 257+ using cf-mysql V33 and have tried V34.  I'm doing the full 3 node MySQL setup with no Arbitrator.  This is on sphere environment.

 This error is repeating in the logs on the broker even after adding jobs.cf-mysql-broker_z1.skip_ssl_validation: true and re-deploy.

From db_migrate.combined.log:

Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
Migrations failed at Thu May  4 14:12:35 UTC 2017
mysql_broker already exists
rake aborted!
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

From broker quota_enforcer.stdout.log:
`{"timestamp":"1493907717.695639133","source":"Quota Enforcer","message":"Quota Enforcer.Looking for violators","log_level":1,"data":{}}
{"timestamp":"1493907717.696820259","source":"Quota Enforcer","message":"Quota Enforcer.Enforcing Failed","log_level":2,"data":{"error":"Finding violators: Error executing 'quota violator'.All: Error 1146: Table 'mys`

From cf-mysql.yml:
`- instances: 1
  name: cf-mysql-broker_z1
  networks:
  - name: mysql1
  resource_pool: cf-mysql-broker_z1
  templates:
  - consumes:
      mysql: nil
      proxy: nil
    name: cf-mysql-broker
    release: cf-mysql
  skip_ssl_validation: true
`

This is the error from Bosh:

  Started updating instance cf-mysql-broker_z1 > cf-mysql-broker_z1/9aeb2bc7-0327-4b0f-b052-fc4317a692bd (0) (canary). Failed: 'cf-mysql-broker_z1/0 (9aeb2bc7-0327-4b0f-b052-fc4317a692bd)' is not running after update. Review logs for failed jobs: cf-mysql-broker, quota-enforcer (00:10:41)

Error 400007: 'cf-mysql-broker_z1/0 (9aeb2bc7-0327-4b0f-b052-fc4317a692bd)' is not running after update. Review logs for failed jobs: cf-mysql-broker, quota-enforcer

Thanks Ray

**Comment by rdoerr01** [comment]
Here are the config files.

<script src="https://gist.github.com/rdoerr01/44d1c4e882c6bb4bfd12228c32ba5cc8.js"></script>

**Comment by GarfieldIsAPhilosopher** [comment]
Hi Ray

The current skip_ssl_validation is set incorrectly, you could remove these lines, and change this line to true
https://gist.github.com/rdoerr01/9af6c044d98a0be64670e3aea88f1fe4#file-cf-mysql-yml-L232

If this still does not fix the problem, could you provide logs for the failing job "cf-mysql-broker, quota-enforcer"? Thanks

**Comment by ryanjjones10** [comment]
Hi Ray,

Since it has been a couple weeks since we have heard from you, we are going to close it out. Please let us know if you have any other question or changes needed.

**Comment by rdoerr01** [comment]
Thanks, did did correct my issue, thanks for the help.
