### ISSUE TITLE
how to gen bosh2.0 cf-mysql-deployment.yml？

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/cf-mysql-release#168]
please help me！ ths。

**Comment by utricularian** [comment]
@bxlkm [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment#cloud-foundry-mysql-bosh-deployment) utilizes BOSH 2.0 features and is only compatible with the BOSH 2.0 cli. Give it a try and let us know if you have any questions.

**Comment by menicosia** [comment]
Please let us know if the `README.md` in cf-mysql-deployment works for you. You can create an issue here on GitHub or if you prefer, you can find us on Slack: https://slack.cloudfoundry.org/ in the `#core-services` channel.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
