### ISSUE TITLE
Using cf-mysql-release as the highly available database for cloud foundry (uaa,cc,diego) and bosh 

### ISSUE THREAD

**Issue by alexwo** [cloudfoundry/cf-mysql-release#173]
Will this be a valid scenario to have cloudfoundry and bosh releases configured to use the cf-mysql-release. This can basically allow to run a highly available mysql serving  bosh, uaa, diegodb, and cf schemas: 
- ccdb
- bosh
- uaad
- diegodb
 
Given the following constraints as documented here regarding the mariadb galera cluster, is this something cloudfoundry & bosh can work with ? or plan to have enabled ?
https://mariadb.com/kb/en/mariadb/mariadb-galera-cluster-known-limitations/

Using this release for cf components was also suggested by @dsabeti here:
https://github.com/cloudfoundry/cf-release/issues/1097 

Your feedback is very much appreciated ! 
Thanks,
Alex

**Comment by GETandSELECT** [comment]
[Swisscom](http://developer.swisscom.com/) uses cf-mysql-release as a backend database for Cloud Foundry components. We are very happy with it. Pivotal does a great job. Prior to use cf-mysql-release we used a custom Puppet Module for MySQL, which had lots of issues. 

Our architects decided against Postgres, mainly because it's harder to operate. Our CF team needs to operate and understand only one relational DB, we use cf-mysql-release for DBaaS and our own DB (CF components backend).

**Comment by jpalermo** [comment]
[cf-deployment](https://github.com/cloudfoundry/cf-deployment) already uses cf-mysql release as the default backing store. This is a relatively new change away from the single node postgres database I believe. I'm not sure if this is the current long term plan or not though, @dsabeti would probably have more insight on that.

**Comment by menicosia** [comment]
@GETandSELECT drop me an e-mail, I'd love to hear more!

**Comment by menicosia** [comment]
@alexwo each of the components (UAA, CC, Diego, etc) are expected to be able to run on any generic Postgres and MySQL. That includes `cf-postgres` and `cf-mysql`. For `cf-mysql`, the development teams are aware of the Galera limitations.

As stated above, there are people who use `cf-release` with `cf-mysql-release`, which you can run in clustered configuration. Doing so allows fast fail-overs when upgrading software or in the event of a failure. Documentation on how to deploy in this configuration is covered in the [cluster behavior](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/docs/cluster-behavior.md#scaling-the-cluster) and [Proxy](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/docs/proxy.md#proxy-count) documentation.

Note that the default configuration of [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment) is clustered-mode.

I'll go ahead and close this Issue for now, but of course you should feel free to re-open if you have any further questions on this topic, or open a new Issue if you have new questions.

Let me know how it goes!

---

  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment]
Oh just a quick follow up, I think the BOSH Director is designed to work with Postgres only. It does not take advantage of clustered MySQL.

/cc @cppforlife

**Comment by GETandSELECT** [comment]
@cppforlife and @menicosia 

We (Swisscom) use MySQL also for BOSH Director. It works fine.
