### ISSUE TITLE
Can I create new Blank datatbase  ?

### ISSUE THREAD

**Issue by bhushanrade** [cloudfoundry/cf-mysql-release#177]
I push one application but showing error 
```
2017-07-26T19:27:32.15+0530 [APP/PROC/WEB/0]OUT Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with
 name 'identityZoneProvisioning' defined in ServletContext resource [/WEB-INF/spring/multitenant-endpoints.xml]: Cannot resolve reference to
 bean 'jdbcTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error
creating bean with name 'flyway' defined in class path resource [spring/data-source.xml]: Invocation of init method failed; nested exception
 is org.flywaydb.core.api.FlywayException: Schema `cf_01daf5a9_c212_4119_9ad0_7b7c6b40ea0e` contains a failed migration to version 1.5.2 !
```

I think the application didn't take default created database ?

**Comment by menicosia** [comment]
Hi @bhushanrade,

Can you show the output of `cf env [appname]`?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by bhushanrade** [comment]
System-Provided:
{
 "VCAP_SERVICES": {
  "mysql": [
   {
    "credentials": {
     "hostname": "10.0.6.11",
     "jdbcUrl": "jdbc:mysql://10.0.6.11:3306/cf_01daf5a9_c212_4119_9ad0_7b7c6b40ea0e?user=FVMLZepCGF6ttNit\u0026password=EToYYKLJ1RuJavnS",
     "name": "cf_01daf5a9_c212_4119_9ad0_7b7c6b40ea0e",
     "password": "EToYYKLJ1RuJavnS",
     "port": 3306,
     "uri": "mysql://FVMLZepCGF6ttNit:EToYYKLJ1RuJavnS@10.0.6.11:3306/cf_01daf5a9_c212_4119_9ad0_7b7c6b40ea0e?reconnect=true",
     "username": "FVMLZepCGF6ttNit"
    },
    "label": "mysql",
    "name": "uisamysql",
    "plan": "default",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "mysql"
    ],
    "volume_mounts": []
   }
  ]
 }
}

{
 "VCAP_APPLICATION": {
  "application_id": "0de1ac72-5515-4386-889e-19d0d4b443e8",
  "application_name": "myuaa2017",
  "application_uris": [
   "myuaa2017.apps.eu01.cf.canopy-cloud.com"
  ],
  "application_version": "1126275a-2bed-47ed-8153-57bed4117a35",
  "cf_api": "https://api.sys.eu01.cf.canopy-cloud.com",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 1024
  },
  "name": "myuaa2017",
  "space_id": "7f589b02-2c5b-4b2e-b2f9-b0aa68fea4f8",
  "space_name": "Space_training",
  "uris": [
   "myuaa2017.apps.eu01.cf.canopy-cloud.com"
  ],
  "users": null,
  "version": "1126275a-2bed-47ed-8153-57bed4117a35"
 }
}

User-Provided:
JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: [enabled: true]
JBP_CONFIG_TOMCAT: {tomcat: { version: 8.0.+ }}
SPRING_PROFILES_ACTIVE: mysql,default
UAA_CONFIG_YAML: uaa.url: http://myuaa2017.apps.eu01.cf.canopy-cloud.com
login.url: http://myuaa2017.apps.eu01.cf.canopy-cloud.com
smtp:
  host: mail.server.host
  port: 3535


No running env variables have been set

No staging env variables have been set

**Comment by menicosia** [comment]
@nebhale any insight? This seems to be properly bound to a cf-mysql service instance...

**Comment by nebhale** [comment]
The connection to MySQL is fine; the fact that Flyway has attempted to do its migrations (and some succeeded) indicates that.  The error message from Flyway indicates that it was unable to successfully apply one of its migrations (the version number indicates which one failed) and could be due to anything from an intermittent failure on the database server, to a schema or data in the schema being invalid for the migration as it was applied.  The Flyway documentation describes how you might go about [repairing](https://flywaydb.org/documentation/faq.html#repair) the problem in the database, but the key is that this has nothing to do with Cloud Foundry, rather the schema and data currently in the database.

**Comment by bhushanrade** [comment]
But same application with mysql service is working fine on local machine
(localhost)
If there is any fault inside code same flyway error should to be promoted,
when I deployment app on localhost

**Comment by nebhale** [comment]
MySQL instances can be configured in myriad ways.  For example, choosing InnoDB or MyISM determines whether transactions are ACID, leading to different behaviors during migrations.  Configuring the character encoding for the database (`utf-8`, `latin1`, etc.) can affect what the names of the tables and columns are allowed to be, as well as the contents of the rows of those tables.

The take away here is that unless you configure your local database to be **identical** to the one created by the `cf-mysql` service, you cannot assume that
> any fault inside code same flyway error (whatever I got on CF) should to be displayed,
when I deployed app on localhost

Your migrations would need to either enforce the configuration of the databases (`ALTER DATABASE ...`) or they would need to be more flexible in allowing configurations that are different but still usable.

**Comment by menicosia** [comment]
@bhushanrade any update on whether @nebhale's information was sufficient to resolve your issue?

**Comment by menicosia** [comment]
Closing, we assume that you've been able to move past this! Feel free to re-open or create a new issue if you need help in the future.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
