### ISSUE TITLE
Deploying without Service Broker

### ISSUE THREAD

**Issue by bkez322** [cloudfoundry/cf-mysql-release#178]
I'm interested in deploying a highly-available MariaDB cluster, but I only need a single cluster, and therefore (I don't think) the service broker is of any benefit to me. How straightforward would it be to deploy a single cluster without using the service broker or any Cloud Foundry integration, using this release?

**Comment by menicosia** [comment]
Hi @bkez322,

You can certainly deploy `cf-mysql-release` using [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment) without a broker. In fact, that's the default behavior unless you also use the [operations/add-broker.yml](https://github.com/cloudfoundry/cf-mysql-deployment/blob/master/operations/add-broker.yml) operations file when deploying.

`cf-mysql-release` does rely on a CF being present, however. Among other things, the proxies register their web UI with the gorouter. There could be additional work to make it run completely standalone, but that hasn't been a priority yet.

---

  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by bkez322** [comment]
Ah, I didn't realize that the database itself without the broker was dependent on Cloud Foundry. Cloud Foundry is already deployed and available in my work environment, so this is certainly an option. I was, however, hoping to find as simple, ready-to-go, and easy-to-administrate a BOSH release of a SQL deployment for my needs as possible. 

Is Cloud Foundry only necessary for things like the web ui (which I could do without), or does the core database part of the deployment fundamentally rely on Cloud Foundry being present to work correctly?

**Comment by zankich** [comment]
@bkez322 without a Cloud Foundry you will not be able to see the web ui for the proxies, but you will be able to use the MySQL deployment without a Cloud Foundry. 

The base [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment/blob/55c4b625f12f9c8f6b5ebe7a8abb18a839f1d0cb/cf-mysql-deployment.yml) manifest makes no assumptions of the presence of a Cloud Foundry, so you can use cf-mysql-release as a standalone MySQL cluster.

**Comment by bkez322** [comment]
@zankich Cool, I'll probably try this out then, thanks
