### ISSUE TITLE
Uploading Release Error

### ISSUE THREAD

**Issue by bkez322** [cloudfoundry/cf-mysql-release#179]
I do:

`wget https://github.com/cloudfoundry/cf-mysql-release/archive/v36.tar.gz`
`bosh -e my-env upload-release v36.tar.gz`

And get this error:

```
Reading manifest '/Users/localadmin/.bosh/tmp/bosh-release012160136/release.MF':
  Opening file /Users/localadmin/.bosh/tmp/bosh-release012160136/release.MF:
    open /Users/localadmin/.bosh/tmp/bosh-release012160136/release.MF: no such file or directory

Exit code 1
```

Is there something more I'm supposed to do to make the final release upload-able? v35 gives me the same error. I am able to upload releases other than cf-mysql-release's just fine to my director.

I understand there are directions here (https://github.com/cloudfoundry/cf-mysql-deployment) to create a release yourself. Is this intended for people to have to do even for final releases?

**Comment by menicosia** [comment]
Hi there @bkez322,

I think I know what's going on. You've grabbed the link at the bottom of the release notes and given that to BOSH. But it's not actually a BOSH release, that's a link to the source code.

I'm sorry, we recently stopped attaching the BOSH releases at the bottom of the release notes. We used to do this up till v34, but as of v35 [[#139611695](https://www.pivotaltracker.com/story/show/139611695)], we stopped.

The official place for downloading BOSH releases is https://bosh.io/, here's a link to [cf-mysql-release v36](https://bosh.io/d/github.com/cloudfoundry/cf-mysql-release?v=36).

Does getting releases from https://bosh.io/ work for you, or is there a need for us to continue attaching the release to the release notes, as we used to?

---

Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by bkez322** [comment]
Ah, I was pretty sure I was just downloading source code and not an actual release, but I didn't see anything else on the page that could possibly be the release so I just went along with it.

Downloading from bosh.io is perfectly fine for me. Perhaps the "Downloading a Stable Release" section of the readme should direct people to bosh.io, as I personally did not find that clear. But in any case, thanks for the help.

**Comment by menicosia** [comment]
OKay, hopefully this [commit](https://github.com/cloudfoundry/cf-mysql-release/commit/dd0fc0d26aab346dbda979cbc31d445e913cc15c) makes things clearer!
