### ISSUE TITLE
Mysql service instance dashboard is not accessible

### ISSUE THREAD

**Issue by roninby** [cloudfoundry/cf-mysql-release#180]
Hello,

 As I know,  Mysql Broker is accessible on http port 8081 by default, so I added a Load Balancer with SSL termination enabled in front of the Mysql Broker, to forward https requests to the backend Mysql Broker listening on port 8081.  Then, Mysql service instances can be created successfully using cf cli. 

The problem is that the service instance dashboard is not accessible. From the Mysql Broker logs, it looks like the requests to Mysql Service Dashboard are all redirected back to https.

```
I, [2017-08-08T05:00:22.441188 #4794]  INFO -- : Processing by Manage::InstancesController#show as HTML
I, [2017-08-08T05:00:22.441471 #4794]  INFO -- :   Parameters: {"id"=>"7f4e6def-39c4-4b1b-969c-a236bcf37a1c"}
I, [2017-08-08T05:00:22.442670 #4794]  INFO -- : Redirected to https://10.11.0.31:8081/manage/instances/7f4e6def-39c4-4b1b-969c-a236bcf37a1c
I, [2017-08-08T05:00:22.442998 #4794]  INFO -- : Filter chain halted as :redirect_ssl rendered or redirected
I, [2017-08-08T05:00:22.443389 #4794]  INFO -- : Completed 302 Found in 2ms (ActiveRecord: 0.0ms)
172.31.2.102 - - [08/Aug/2017:05:00:22 +0000] "GET /manage/instances/7f4e6def-39c4-4b1b-969c-a236bcf37a1c HTTP/1.1" 302 - 0.0107
I, [2017-08-08T07:35:38.777050 #4797]  INFO -- : Started GET "/manage/instances/7f4e6def-39c4-4b1b-969c-a236bcf37a1c" for 172.31.2.102 at 2017-08-08 07:35:38 +0000
```

After reading [the official statements](https://github.com/cloudfoundry/cf-mysql-release#require-https-when-visiting-dashboard),  I'm still confused: why Mysql Broker need SSL termination, which means it's just listening on http port, however the dashboard URL still require the https scheme?  How can I configure the Load Balance policy to work this out?  

  
```
Broker Configuration

Require HTTPS when visiting Dashboard

The dashboard URL defaults to using the https scheme. This means any requests using http will automatically be redirected to https instead. To override this, you can change jobs.cf-mysql-broker.ssl_enabled to false.

Keep in mind that changing the ssl_enabled setting for an existing broker will not update previously advertised dashboard URLs. Visiting the old URL may fail if you are using the SSO integration, because the OAuth2 client registered with UAA will expect users to both come from and return to a URI using the scheme implied by the ssl_enabled setting.

Note: If using https, the broker must be reached through an SSL termination proxy. Connecting to the broker directly on https will result in a port 443: Connection refused error.

```

Thanks for any help.

**Comment by menicosia** [comment]
Hi @roninby,

I'm sorry I didn't see this new issue sooner.

You're right that no part of `cf-mysql-release` has SSL-termination built in. It's something we haven't gotten to. Instead, most Operators are OK with terminating SSL above, either at the load balancer or gorouter. However, we didn't want people accidentally using non-SSL when talking with the broker or dashboard, so they look at the X-Protocol header to validate that the protocol was `https`.

Can you double check that your load balancer is passing that header through to Broker?

--

Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by menicosia** [comment]
PS - I think the precise header the broker and switchboard look for is:

> X-Forwarded-Proto: https

Let us know if that works properly for you!

**Comment by roninby** [comment]
@menicosia ,

Thanks for the reply.

I'm using a NSX load balancer (IP: 10.11.0.1 ) in front of the mysql broker (IP: 10.11.0.31), SSL termination has been enabled on the  NSX LB:

![image](https://user-images.githubusercontent.com/10234085/29256670-c87eb2c2-80de-11e7-81ab-a4f94f21c1e3.png)


From the mysql broker's log I've just pasted at the beginning of this issue, it looks like the https request from my browser (IP: 172.31.2.102)  has been passed (with ssl terminated) to the broker by NSX LB, the broker has received the http request but redirected it to https again like `https://10.11.0.31:8081/manage/instances/7f4e6def-39c4-4b1b-969c-a236bcf37a1c`. As the broker only listen on the http port 8081,  the https request failed at the end.

I'm not sure why the broker redirects the http request back to https request? Is there anything I just missed in the broker's configuration?

Thanks.

**Comment by ndhanushkodi** [comment]
@roninby,

We typically don't recommend placing a load balancer in front of the broker.

You should be able to expose the broker directly by configuring the `cf_mysql.external_host` broker property to a URL that your CF router is able to point to the broker. (This would be an https:// url that is a subdomain of your system domain). If you run the `broker-registrar` errand, that `cf_mysql.external_host` URL will be registered with the CF router and will point to your broker.

If you want to have more than one broker instance, the CF router will load-balance traffic across your broker instances.

Oncer you register the broker's route, the default behavior will be for the broker to accept SSL traffic on port 8081.

If your network configuration for some reason prevents you from registering a route by which the broker is made accessible externally, and/or you need to use a load balancer in front of the broker, then you can configure the broker property `cf_mysql.broker.ssl_enabled: false` so that the broker accepts non-ssl traffic from your load balancer. 

Nitya (@ndhanushkodi) and Alex (@stupakov)

**Comment by roninby** [comment]
@ndhanushkodi, 

Many thanks for the clarification. Now it's OK after putting the broker behind the router.

Best Regards

**Comment by menicosia** [comment]
Hi, sounds like @ndhanushkodi and @stupakov got your problem squared away, so I'll close this issue.

As always, you should feel free to either re-open this, or create a new issue, should you get stuck in the future!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
