### ISSUE TITLE
backing up binary logs on S3?

### ISSUE THREAD

**Issue by GETandSELECT** [cloudfoundry/cf-mysql-release#187]
Hey

We use for daily full backup SHIELD from Stark & Wayne. SHIELD has no support for binary backups as far as I know.

Are there any plans to ship or stream binary logs (PITR) to S3 endpoint? Is this on roadmap? Do you have better solution?
Or we better colocate some script?

thanks

**Comment by menicosia** [comment]
Hi @GETandSELECT currently cf-mysql-release doesn't have any facility for log-shipping, sorry!

**Comment by menicosia** [comment]
I'll close this for now, as we do not plan to make any major changes in the immediate future. Please feel free to re-open if there's more to discuss, or if you have any additional questions!
