### ISSUE TITLE
`cf_mysql.mysql.tls.ca_certificate ` not templated into my.cnf

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-mysql-release#200]
Hi,
we have noticed that the `cf_mysql.mysql.tls.ca_certificate` property does not get templated and used to set a value for `ssl_ca` in my.cnf unlike `cf_mysql.mysql.tls.server_certificate` and `cf_mysql.mysql.tls.server_key` for `ssl_cert` and `ssl_key` respectively.

This prevents us from using mutual TLS to authenticate against the MariaDB server. Would you be happy to accept a pull request that fixes this issue?

Thanks!
Giuseppe && @edwardecook

**Comment by zankich** [comment]
@gcapizzi yes we would be happy to accept that PR!

**Comment by jzlwang** [comment]
@gcapizzi woo, old issue. cf-mysql-release has been deprecated, and we're no longer adding new features to it. So, closing this issue.
