### ISSUE TITLE
BOSH BBR failing with 36.14.0

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry/cf-mysql-release#211]
# Bug Report Info
## Currently:

Backup and Restore database restorer fails with 

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory")
```

## Expected:

The BBR script should be able to connect to the MySQL server and perform the backup

## Steps to Reproduce:

* Deploy a service that uses BBR for MySQL
* Try backup the service
* It will fail

The issue seems to have been introduced in 36.12.0 with `cf-mysql-release should no longer write /etc/mysql/my.cnf [#156406871], [#156242509]`. The absence of this file means that the backup and restore executable cannot identify the correct socket location.

## Deployment Context:
Please provide relevant details about your deployment. That might include:
* This is the pks-api-release deployment
* Release version : 36.14.0
* Backup and Restore v1.6.0

```
Error attempting to run backup for job pks-api on pivotal-container-service/ad798457-2d08-433a-954f-00a78e6c222a: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
2018/05/31 13:56:04 ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) - exit code 1
```

**Comment by menicosia** [comment]
Summary:

This is an interesting issue, but we believe that this is possibly related to your usage of the BBR SDK - we believe that CFCR's implementation of the `backup` script required by the BBR contract is incorrectly referring to a socket path when it could equally be specifying `127.0.0.1`. I think this means you are to provide the correct host in the JSON provided as [config options](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release#config-options).

For that reason, we don't believe that you should be looking for a `my.cnf` on the target host; rather pass in the configuration necessary to work with _either_ cf-mysql and pxc-release.

Does that make sense, and is it correct? If not so, please feel free to re-open this issue and we'll be happy to take another look at it.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by bstick12** [comment]
@menicosia Our configurations contains the following information

```
JSON.pretty_generate(
  'username' => 'pks',
  'password' => p('pks.db_password'),
  'host' => 'localhost',
  'port' => 3306,
  'database' => 'pks',
  'adapter' => 'mysql',
)
```

So we have the host and port information specificied

Out backup scripts calls the `backup` command provided by the `database-backup-restorer` SDK

```
"/var/vcap/jobs/database-backup-restorer/bin/backup" --config "${CONFIG_PATH}" --artifact-file "${BBR_ARTIFACT_FILE_PATH}"
```

Perhaps the issue is the with `database-backup-restorer` SDK not using the host information but relying on configured socket information.

**Comment by bstick12** [comment]
@menicosia It looks like using `127.0.0.1` instead of `localhost` fixes the issue. It seems to be a `mysql` client behavior. Thanks for your help.
