### ISSUE TITLE
build-mysql-release fails cf-mysql-release/packages/golang-1.11-linux/spec: no such file or directory

### ISSUE THREAD

**Issue by kumarganesh2814** [cloudfoundry/cf-mysql-release#219]
Thank you for submitting an issue.

## Problem you are trying to solve
Help us understand the problem you are facing. Please provide as much context as possible.
Hi

While running build-mysql-rlease we get below error:
```
build-mysql-release fails cf-mysql-release/packages/golang-1.11-linux/spec: no such file or directory
```

I guess issue that I see cf-mysql-release/packages/golang-1.11-linux/spec.lock file 

Can you please look into this issue 

Best Regards
Ganesh Kumar
## Proposed solution/feature
What is the proposed solution and why do you think it is the best approach to the problem above.

## Would you want to open an PR for this feature?

# Bug Report Info
## Currently:
What is the current broken behavior?

## Expected:
What the correct behavior should be?

## Steps to Reproduce:
Please provide as much detail as possible. 

## Deployment Context:
Please provide relevant details about your deployment. That might include:
* Are you using cf-mysql-release with a service broker?
* How many nodes and proxies are deployed?
* Other relevant deployment topology info
* Release version
* Other bosh releases deployed on the same vms

## Reference:
Attach screenshot(s) or logs if relevant

**Comment by kumarganesh2814** [comment]
Are you using cf-mysql-release with a service broker? Yes
```
        BOSH_ENVIRONMENT: ((bosh_environment))
        CF_MYSQL_BROKER_URL: https://github.com/cloudfoundry/cf-mysql-broker.git
        CF_MYSQL_RELEASE_TAG: v36.16.0
        CF_MYSQL_RELEASE_URL: https://github.com/cloudfoundry/cf-mysql-release.git
```
Other bosh releases deployed on the same vms-->No
How many nodes and proxies are deployed? Nil
New deployment

**Comment by kumarganesh2814** [comment]
ANy update here team

**Comment by kumarganesh2814** [comment]
How to update golang in cf-mysql release also we want maria db 10.1.36 deployed via this pipeline. Please advise.

Best Regards
Ganesh Kumar

**Comment by kumarganesh2814** [comment]
Hey Team,

Any update here please.

Best Regards
Ganesh

**Comment by abg** [comment]
The golang packages are now using [bosh vendored packages](https://bosh.io/docs/package-vendoring/#vendor).  The support was added in bosh-cli v2.0.36.

What version of the bosh-cli are you using?  Is it possible that you are using an old version of the cli to build the release?  I can reproduce a similar error by using a version of the bosh-cli prior to v2.0.36.

If you do not believe that is the case, can you provide the full output from the build script's attempt to run `bosh create-release`?

**Comment by kumarganesh2814** [comment]
Sorry for late update here is output for cf-mysql-build-release and bosh version


root@524be84fe443:/cf-mysql-release# bosh create-release --name cf-mysql-custom --timestamp-version --force --tarball cf-mysql-release.tgz
Blob download 'boost/boost_1_59_0.tar.gz' (84 MB) (id: 9f1801dc-7a8c-4969-a97f-c0432a3a4331 sha1: 5123209db194d66d69a9cfa5af8ff473d5941d97) started
Blob download 'boost/boost_1_59_0.tar.gz' (id: 9f1801dc-7a8c-4969-a97f-c0432a3a4331) finished
Blob download 'check/check-0.9.13.tar.gz' (753 kB) (id: d6c51160-8a67-4290-a337-dbc9d515d08a sha1: 09f682d2239b1353818b74d06099a17460450240) started
Blob download 'check/check-0.9.13.tar.gz' (id: d6c51160-8a67-4290-a337-dbc9d515d08a) finished
Blob download 'cipher_finder/cipher_finder.jar' (22 MB) (id: 4d04bb85-6bae-48bd-72a6-ecbc65962b83 sha1: 374b1a0008dc16ff3c9cf8f91a8424635f2f8eef) started
Blob download 'cipher_finder/cipher_finder.jar' (id: 4d04bb85-6bae-48bd-72a6-ecbc65962b83) finished
Blob download 'cli/cf-cli_6.36.1_linux_x86-64.tgz' (5.9 MB) (id: 3cea6e9c-e3ed-40f2-7929-c07a0ed77149 sha1: faade069c0e7a76cb3bb1c9dfd69da2d340155c9) started
Blob download 'cli/cf-cli_6.36.1_linux_x86-64.tgz' (id: 3cea6e9c-e3ed-40f2-7929-c07a0ed77149) finished
Blob download 'galera/galera-25.3.23.tar.gz' (3.3 MB) (id: 90c147fb-a02a-45c7-5036-2dee134223ac sha1: 000e20ad02113e796a8a551a2733674338fbbc92) started
Blob download 'galera/galera-25.3.23.tar.gz' (id: 90c147fb-a02a-45c7-5036-2dee134223ac) finished
Blob download 'mariadb/mariadb-10.1.36.tar.gz' (63 MB) (id: c197beaf-1799-444f-5263-172b367ee4a9 sha1: 8811cbb28fb1a766359798ffc9d086b86e99c431) started
Blob download 'mariadb/mariadb-10.1.36.tar.gz' (id: c197beaf-1799-444f-5263-172b367ee4a9) finished
Blob download 'mysqlclient/mariadb-connector-c-2.1.0-src.tar.gz' (1.9 MB) (id: e1e0446a-8cbd-4b8e-b496-fc20f530fd7c sha1: 2fea886fd8ddf3e17d6228d282828afeaee0a317) started
Blob download 'mysqlclient/mariadb-connector-c-2.1.0-src.tar.gz' (id: e1e0446a-8cbd-4b8e-b496-fc20f530fd7c) finished
Blob download 'pcre-8.35.tar.gz' (2.0 MB) (id: 34f25eac-2566-45c5-afee-babae9b83f63 sha1: 5a0efc7332c6741114372020a60acfed22befcb9) started
Blob download 'pcre-8.35.tar.gz' (id: 34f25eac-2566-45c5-afee-babae9b83f63) finished
Blob download 'python/Python-2.7.13.tgz' (17 MB) (id: d97aea2b-8036-4b6a-709c-200865a69da1 sha1: dce2b862a30099ee48c19a7c34e2d7c2eeff5670) started
Blob download 'python/Python-2.7.13.tgz' (id: d97aea2b-8036-4b6a-709c-200865a69da1) finished
Blob download 'ruby/ruby-2.3.8.tar.gz' (18 MB) (id: 8f9fd1fa-5198-4fec-5a2c-4b9d7ea34c97 sha1: 69311991a9cd2c8e3c86a0dbbaaf915ae91f0bec) started
Blob download 'ruby/ruby-2.3.8.tar.gz' (id: 8f9fd1fa-5198-4fec-5a2c-4b9d7ea34c97) finished
Blob download 'ruby/rubygems-2.7.6.tgz' (852 kB) (id: e3c0b159-a925-48a0-4fe0-e7b3dcc5dcf4 sha1: 72a14791b96cc05a79d2a649fe7170fd1faf3e0a) started
Blob download 'ruby/rubygems-2.7.6.tgz' (id: e3c0b159-a925-48a0-4fe0-e7b3dcc5dcf4) finished
Blob download 'ruby/yaml-0.1.7.tar.gz' (528 kB) (id: 4f10a1e8-949e-4d9b-6e49-fabe5cba6fc0 sha1: 3590cbf092ef4c71bc0a9b404c00a626b1e04dee) started
Blob download 'ruby/yaml-0.1.7.tar.gz' (id: 4f10a1e8-949e-4d9b-6e49-fabe5cba6fc0) finished
Blob download 'scons/scons-2.3.1.tar.gz' (499 kB) (id: e3136aa7-9bf6-4c49-a26d-9ebe85665818 sha1: 775e715e49fe5fd8e1d29551a296fdc9267509e7) started
Blob download 'scons/scons-2.3.1.tar.gz' (id: e3136aa7-9bf6-4c49-a26d-9ebe85665818) finished
Blob download 'xtrabackup/autoconf-2.65.tar.gz' (1.7 MB) (id: 12402e0c-14bd-4a31-8344-858c09639f67 sha1: ae9e1ab046822007f25c88e1d8f2166e065da8c2) started
Blob download 'xtrabackup/autoconf-2.65.tar.gz' (id: 12402e0c-14bd-4a31-8344-858c09639f67) finished
Blob download 'xtrabackup/automake-1.14.1.tar.gz' (2.2 MB) (id: 22110fae-0404-48d2-a2a0-869b40172c09 sha1: 0bb1714b78d70cab9907d2013082978a28f48a46) started
Blob download 'xtrabackup/automake-1.14.1.tar.gz' (id: 22110fae-0404-48d2-a2a0-869b40172c09) finished
Blob download 'xtrabackup/libaio_0.3.110.orig.tar.gz' (42 kB) (id: 10d3be70-6c51-4220-9d46-8de75281fd3d sha1: f8f6ed15f22e528f6f415939b07854539e3360e4) started
Blob download 'xtrabackup/libaio_0.3.110.orig.tar.gz' (id: 10d3be70-6c51-4220-9d46-8de75281fd3d) finished
Blob download 'xtrabackup/libev-4.22.tar.gz' (530 kB) (id: 023ba1e4-a21c-44f8-8c7d-51933bb0a3c9 sha1: b5cc3f6d8d842e23fccc9b27d318ae7fa3d3bf60) started
Blob download 'xtrabackup/libev-4.22.tar.gz' (id: 023ba1e4-a21c-44f8-8c7d-51933bb0a3c9) finished
Blob download 'xtrabackup/libtool-2.4.2.tar.gz' (2.6 MB) (id: 958f3335-2373-4c4f-9db1-7391a9a7e6f2 sha1: 22b71a8b5ce3ad86e1094e7285981cae10e6ff88) started
Blob download 'xtrabackup/libtool-2.4.2.tar.gz' (id: 958f3335-2373-4c4f-9db1-7391a9a7e6f2) finished
Blob download 'xtrabackup/percona-xtrabackup-2.4.8.tar.gz' (58 MB) (id: ca08f6b1-14a5-45f7-4e57-df362b2fcb8a sha1: 5cc6b689b9682923211f9aace7ec6c6d22b69346) started
Blob download 'xtrabackup/percona-xtrabackup-2.4.8.tar.gz' (id: ca08f6b1-14a5-45f7-4e57-df362b2fcb8a) finished
Blob download 'xtrabackup/socat-1.7.3.2.tar.gz' (612 kB) (id: ba6cfda8-0c00-451e-6338-2007ef503d56 sha1: 28eca1f8efeadde3f96c1ac89e553c28d736d41d) started
Blob download 'xtrabackup/socat-1.7.3.2.tar.gz' (id: ba6cfda8-0c00-451e-6338-2007ef503d56) finished

Building a release from directory '/cf-mysql-release':
  - Constructing packages from directory:
      - Reading package from '/cf-mysql-release/packages/golang-1.11-linux':
          Collecting package files:
            Reading package spec '/cf-mysql-release/packages/golang-1.11-linux/spec':
              Opening file /cf-mysql-release/packages/golang-1.11-linux/spec:
                open /cf-mysql-release/packages/golang-1.11-linux/spec: no such file or directory
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'acceptance-tests'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'bootstrap'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'cf-mysql-cluster-health-logger'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'galera-healthcheck'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'generate-auto-tune-mysql'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'gra-log-purger'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'mariadb_ctrl'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'quota-enforcer'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of package 'switchboard'
  - Constructing jobs from manifest:
      - Expected to find package 'mariadb' since it's a dependency of job 'arbitrator'
      - Expected to find package 'bootstrap' since it's a dependency of job 'bootstrap'
      - Expected to find package 'cli' since it's a dependency of job 'broker-registrar'
      - Expected to find package 'ruby' since it's a dependency of job 'cf-mysql-broker'
      - Expected to find package 'cli' since it's a dependency of job 'deregister-and-purge-instances'
      - Expected to find package 'xtrabackup' since it's a dependency of job 'mysql'
      - Expected to find package 'switchboard' since it's a dependency of job 'proxy'
      - Expected to find package 'bootstrap' since it's a dependency of job 'rejoin-unsafe'
      - Expected to find package 'golang-1.11-linux' since it's a dependency of job 'smoke-tests'
      - Expected to find package 'mariadb' since it's a dependency of job 'verify-cluster-schemas'

Exit code 1
root@524be84fe443:/cf-mysql-release# bosh -n upload-release cf-mysql-release.tgz

root@524be84fe443:/cf-mysql-release# bosh -v
version 2.0.28-cb77557-2017-07-11T23:04:21Z

Succeeded

**Comment by kumarganesh2814** [comment]
@abg 

Thanks for input it was issue with bosh version

I created new image of docker with latest bosh version 5 

Now we are able to build mysql release without any issue.

          type: docker-image
          source:
            repository: ganeshdevops10/cf-bosh
            tag: bosh5

**Comment by APShirley** [comment]
Closing this as it has been resolved by using a newer version of bosh that supports vendored packages.
Thanks,
Al
