### ISSUE TITLE
errand "broker-registrar" fails

### ISSUE THREAD

**Issue by akranga** [cloudfoundry/cf-mysql-release#24]
Trying to run broker-registrar errand... it fails with error

```
Task 257 done

Started         2014-07-21 15:36:09 UTC
Finished        2014-07-21 15:39:16 UTC
Duration        00:03:07

[stdout]

bundle exec ./bin/broker-registrar register
    --cf-address https://api.cf.abc.def
    --cf-username admin
    --cf-password ********
    --broker-name p-mysql
    --broker-url http://p-mysql.pcf.cf.abc.def:80
    --broker-username admin
    --broker-password ********


[stderr]
E, [2014-07-21T15:36:48.444016 #3290] ERROR -- : 10001: The service broker API returned an error from http://p-mysql.pcf.cf.abc.def/v2/catalog: 404 Not Found (CFoundry::ServerError)
```

**Comment by suchakra012** [comment]
Trying to run mysql broker with  broker-registrar errand. But it throws an error ->

[stderr]
E, [2016-08-09T19:22:49.380743 #3540] ERROR -- : Connection timed out - connect(2) (Errno::ETIMEDOUT)
/var/vcap/packages/ruby/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
/var/vcap/packages/ruby/lib/ruby/2.0.0/net/http.rb:878:in `open'
/var/vcap/packages/ruby/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
/var/vcap/packages/ruby/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
/var/vcap/packages/ruby/lib/ruby/2.0.0/net/http.rb:877:in `connect'
/var/vcap/packages/ruby/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/var/vcap/packages/ruby/lib/ruby/2.0.0/net/http.rb:851:in `start'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/rest_client.rb:148:in `request_uri'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/rest_client.rb:60:in `request'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:93:in `request_raw'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:88:in `request'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:66:in `get'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:62:in `info'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:29:in `uaa'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/concerns/login_helpers.rb:10:in `login'
/var/vcap/data/packages/broker-registrar/1.1/vendor/bundle/ruby/2.0.0/gems/cfoundry-4.7.1/lib/cfoundry/v2/client.rb:50:in `login'
/var/vcap/data/packages/broker-registrar/1.1/lib/broker_registrar.rb:12:in `register'

Tried creating the service manually, still it fails .
any help here.
