### ISSUE TITLE
No Bundle or .ruby-version

### ISSUE THREAD

**Issue by tlabeeuw** [cloudfoundry/cf-mysql-release#40]
Hi,

Unlike cf-release which has a .ruby-version and bundle file there is none for this repo. Not really a big issue but nice to know exactly which Ruby and Bosh version we should be using.

Thanks,

@tlabeeuw @weymanf

**Comment by robdimsdale** [comment]
@tlabeeuw @weymanf

We've added a `.ruby-version` file. We haven't added a `Gemfile` because we have no need for it - the only gem we use is `bosh_cli` and we're using a variety of versions of that gem with no side-effects.

Marking this as closed - feel free to reopen if you have further issues.
