### ISSUE TITLE
some question about shut down all nodes！

### ISSUE THREAD

**Issue by HelloLin** [cloudfoundry/cf-mysql-release#48]
hello, i am using mariadb as a database cluster, but i  have some question. 

1. i read the code of mariadb_ctrl, finding that it does not deal with the situation when all nodes shut down, and restart together. maybe we need to bootstrap one node when all node is unreachable. but it still join?? i deploy it in openstack, and it real does not work, when all nodes shut down. 

2. i deploy 3 node mysql/0, mysql/1, mysql/2. first i stop mysql/0, and insert some data to mysql/1 and mysql/2. then stop all node. after i restart all nodes(bootstrap in mysql/0). mysql/1 and mysql/2 can not to join the cluster, because of the /var/vcap/store/mysql/grastate.dat seqno is greater than mysql/0. if i delete the grastate.dat it can join the cluster, but i lose some data. so i want to know how you deal with this question? 

thank you for your answer.

**Comment by shalako** [comment]
Nothing to add. @HelloLin We don't know of a good way to automate bootstrapping when all nodes have failed. Closing this for now; if you have a good idea please let us know.
