### ISSUE TITLE
Is it possible to run this without a CF?

### ISSUE THREAD

**Issue by bendodd** [cloudfoundry/cf-mysql-release#56]
Is it possible to run this without a CF? I.e. use the API to create DB instances directly

Thanks!

**Comment by menicosia** [comment]
Hi Benedict,

Sorry for taking so long to get back to you on this. We absolutely do plan to make it possible to auto-deploy MySQL with HA configuration separately from CF. It's a prioritized in our roadmap, but not yet scheduled or staffed.

We'll notify you as it approaches execution phase. Thank you!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by drnic** [comment]
BTW it can be deployed without CF - the broker itself has no required knowledge of CF - it's API could be called directly to create services, bind to get credentials etc.

**Comment by bendodd** [comment]
Thanks for your response @menicosia ; it's very much appreciated!

@drnic Any tips on doing this? The generated bosh-lite config failed to complete without a CF available

**Comment by menicosia** [comment]
Hi @drnic, unfortunately right now our components expect to communicate over NATS with CF-release (e.g. route registration). So unfortunately, we'll have to work through a couple of dependencies before you really can deploy independent of CF.

As mentioned above, you can follow the progress of this issue at https://www.pivotaltracker.com/n/projects/969486/stories/90523652

-- Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by drnic** [comment]
Benedict - try modifying the monit scripts to disable the route-registrar process as Marco mentioned above. Eg route-registrar only required if cf nats properties provided.

**Comment by bendodd** [comment]
@drnic Thanks for your suggestion

I've got as far as a completing bosh deployment to BOSH Lite by removing the monit config for route-registrar, although I have a failing cf-mysql-broker

less /var/vcap/sys/log/cf-mysql-broker/cf-mysql-broker.log 

```
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection timed out - connect(2) for "api.10.244.0.34.xip.io" port 443 (Errno::ETIMEDOUT)
        from /var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:879:in `open'
        from /var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
        from /var/vcap/packages/ruby/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:878:in `connect'
        from /var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from /var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:1369:in `request'
        from /var/vcap/data/packages/cf-mysql-broker/aa7825a497a7c4f4e502fe4e5d69f91b1ab63469.1-4162c3421d14fb9ea881b27fd8731bff092c4a98/app/models/cloud_controller_http_client.rb:14:in `get'
        from /var/vcap/data/packages/cf-mysql-broker/aa7825a497a7c4f4e502fe4e5d69f91b1ab63469.1-4162c3421d14fb9ea881b27fd8731bff092c4a98/lib/configuration.rb:28:in `cc_api_info'
        from /var/vcap/data/packages/cf-mysql-broker/aa7825a497a7c4f4e502fe4e5d69f91b1ab63469.1-4162c3421d14fb9ea881b27fd8731bff092c4a98/lib/configuration.rb:17:in `auth_server_url'
        from /var/vcap/data/packages/cf-mysql-broker/aa7825a497a7c4f4e502fe4e5d69f91b1ab63469.1-4162c3421d14fb9ea881b27fd8731bff092c4a98/config/initializers/omniauth.rb:10:in `block in <top (required
)>'
        from /var/
```

**Comment by gerhard** [comment]
Just submitted this #77

**Comment by evanshort73** [comment]
Hi @gerhard, thanks for submitting a pull request!

It just so happens the team started working on a CF-less release recently. We'll evaluate your pull request within the context of the work we've done so far

**Comment by zankich** [comment]
The base deployment manifest in [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment/tree/1ab0f685bd64506f5dd9d310b412e8b29ff2d49b) does not require a CF and does not include the broker. A broker can be added to the deployment manifest with the [add-broker](https://github.com/cloudfoundry/cf-mysql-deployment/blob/1ab0f685bd64506f5dd9d310b412e8b29ff2d49b/operations/add-broker.yml) opsfile, although that opsfile assumes that a CF will be available.
