### ISSUE TITLE
No release notes for v20

### ISSUE THREAD

**Issue by scotttag** [cloudfoundry/cf-mysql-release#66]
Release notes seem to still be missing for v20 over 2 weeks after release. Not sure if this is an omission?

**Comment by menicosia** [comment]
Hi @scottag,

Yep, this is an unintentional omission. I messed up and forgot to post them. I will have them up shortly, and I am sorry for the "mystery stealth release!" Thanks for pinging us on this.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by scotttag** [comment]
No worries, thanks Marco :-)

**Comment by menicosia** [comment]
[v20 release notes](https://github.com/cloudfoundry/cf-mysql-release/releases/tag/v20)

Upgrading on AWS is unavoidably tedious. Please let me know if you notice any errors, I'll fix them ASAP!

Closing, thank you again.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
