### ISSUE TITLE
loadbalancing read query's

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/cf-mysql-release#72]
i was wondering if you are also working on load-balancing the read queries between the slave nodes

**Comment by menicosia** [comment]
Hi @ramonskie,

We plan to.

For the time being, the priority has been to make the MySQL service very durable and accessible.

We have a couple of stories that will eventually lead to an Operator's ability to more flexibly distribute load across the cluster - one approach is to make our own SwitchBoard smarter, #[78679522](https://www.pivotaltracker.com/story/show/78679522). The other is qualifying if [MaxScale](https://mariadb.com/products/mariadb-maxscale) is now a good match for our typical users' needs, #[94963146](https://www.pivotaltracker.com/story/show/94963146). MaxScale's pretty powerful and flexible, so we're hopeful that we'll be able to bring it into our service at some point in the future.

Is this something you're interested in collaborating with us on?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment]
Hi, I haven't heard a response, so I'm going to close this issue for now. This is on our radar, but nothing specific to cover at this time.

As always, please feel free to re-open at any time.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by ramonskie** [comment]
sorry for the late reply. totally forgot about this.
but maxscale seems to be the way to go
