### ISSUE TITLE
create release fails on No artifact found for cf-mysql-broker

### ISSUE THREAD

**Issue by naheedmk** [cloudfoundry/cf-mysql-release#74]
Hi 
Getting following error while creating release. Looking forward for any pointers to move forward.

Thanks
Naheed

Building xtrabackup...
  Using final version '2e701e7a9e4241b28052d984733de36aae152275'

Building cf-mysql-broker...
  No artifact found for cf-mysql-broker
  Generating...
  Pre-packaging...
  > + set -e
  > + cd /home/vagrant/tmp/d20150731-31754-12hnjwm/d20150731-31754-1vp8gbx/cf-my
sql-broker
  > + bundle package --all --no-install
  > Unknown switches '--no-install'
'cf-mysql-broker' pre-packaging failed

**Comment by menicosia** [comment]
Hi @naheedmk,

Can you give us more information about what you're trying to do? Are you following a specific set of instructions, are you using a tag or a branch, what IaaS you're using, what commands you've run, etc?

A little more context will help us - this step works reliably in our Continuous Integration environments, so there's likely something odd that we'd need to understand before we might be able to help.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment]
Closing due to no response; please feel free to re-open or open a new issue in the future!

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by simontakite** [comment]
Hello Marco, 

I am testing out cf and deployed it on vagrant .. However, am getting the same error when I run bosh create release. I run this from my local machine and not from the vagrant vm. I have to say, I am new to all this. Thanks

**Comment by ljfranklin** [comment]
@simontakite Can you see if the steps listed in the [Development](https://github.com/cloudfoundry/cf-mysql-release#development) section of the README allow you to create a release? I'm guessing the missing step was running `./update` (which syncs up all the submodules) before running `bosh create release`.

**Comment by ljfranklin** [comment]
@simontakite Or if you just want to install cf-mysql, you can download a final release from [bosh.io](http://bosh.io/releases/github.com/cloudfoundry/cf-mysql-release?all=1).

**Comment by simontakite** [comment]
@ljfranklin Thanks for prompt reply! I finally got it to run with an earlier release with.. bosh upload release releases/cf-mysql-20.yml .. deployment took 86 mins (is that normal?) .. and one job - cf-mysql-broker_z1/0 is always failing(others are ok). Also, is there some short instructions on how to create a mysql service with service plans using this resource: http://gnuconsulting.com/blog/2014/09/21/intro-to-cloud-foundry-and-bosh-part-3/ without any luck either - i would appreciate an official how to on achieving the same. thanks in advance
