### ISSUE TITLE
create service broker error

### ISSUE THREAD

**Issue by jinjing750629** [cloudfoundry/cf-mysql-release#75]
Dear sir,

I got an error when I issue command:

cf create-service-broker p-mysql admin password https://p-mysql.10.244.0.34.xip.io

The service broker could not be reached: https://p-mysql.10.244.0.34.xip.io/v2/catalog

I checked my netstat -nr, the route is correct. I can access https://p-mysql.10.244.0.34.xip.io/v2/catalog via my web browser. 

Anybody can take a look?

Thanks

**Comment by menicosia** [comment]
Hi @jinjing750629,

Can you give us a little background on how you've gotten to this point? Are you following a particular set of instructions, what version you're using, what IaaS are you deploying to, what steps have you completed so far...?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by jinjing750629** [comment]
Marco, I am using bosh-lite to deploy a local instance of CF to my personal mac. I successfully deployed CF and then try to deploy mysql service following the instruction from https://github.com/cloudfoundry/cf-mysql-release/. CF version is 212. Here is the output of "bosh vms" on my mac. Looks like both CF and mysql are working well. But when I try to create the service broker, I got the previous issue.

+------------------------------------+---------+---------------+--------------+
| Job/index                          | State   | Resource Pool | IPs          |
+------------------------------------+---------+---------------+--------------+
| api_z1/0                           | running | large_z1      | 10.244.0.134 |
| consul_z1/0                        | running | medium_z1     | 10.244.0.54  |
| doppler_z1/0                       | running | medium_z1     | 10.244.0.142 |
| etcd_z1/0                          | running | medium_z1     | 10.244.0.42  |
| ha_proxy_z1/0                      | running | router_z1     | 10.244.0.34  |
| hm9000_z1/0                        | running | medium_z1     | 10.244.0.138 |
| loggregator_trafficcontroller_z1/0 | running | small_z1      | 10.244.0.146 |
| nats_z1/0                          | running | medium_z1     | 10.244.0.6   |
| postgres_z1/0                      | running | medium_z1     | 10.244.0.30  |
| router_z1/0                        | running | router_z1     | 10.244.0.22  |
| runner_z1/0                        | running | runner_z1     | 10.244.0.26  |
| uaa_z1/0                           | running | medium_z1     | 10.244.0.130 |
+------------------------------------+---------+---------------+--------------+

VMs total: 12
Deployment `cf-warden-mysql'

Director task 407

Task 407 done

+----------------------+---------+--------------------+--------------+
| Job/index            | State   | Resource Pool      | IPs          |
+----------------------+---------+--------------------+--------------+
| cf-mysql-broker_z1/0 | running | cf-mysql-broker_z1 | 10.244.7.130 |
| cf-mysql-broker_z2/0 | running | cf-mysql-broker_z2 | 10.244.8.130 |
| mysql_z1/0           | running | mysql_z1           | 10.244.7.2   |
| mysql_z2/0           | running | mysql_z2           | 10.244.8.2   |
| mysql_z3/0           | running | mysql_z3           | 10.244.9.2   |
| proxy_z1/0           | running | proxy_z1           | 10.244.7.6   |
| proxy_z2/0           | running | proxy_z2           | 10.244.8.6   |
+----------------------+---------+--------------------+--------------+

**Comment by jinjing750629** [comment]
More error log

jjin-mac:bosh-lite jjin$ sudo bosh run errand broker-registrar
Acting as user 'admin' on deployment 'cf-warden-mysql' on 'Bosh Lite Director'

Director task 355
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:00)
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)
     Done preparing deployment (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started creating bound missing vms > errands_z1/0. Done (00:00:02)

  Started binding instance vms > broker-registrar/0. Done (00:00:00)

  Started updating job broker-registrar > broker-registrar/0 (canary). Done (00:00:38)

  Started running errand > broker-registrar/0. Done (00:00:16)

  Started fetching logs for broker-registrar/0 > Finding and packing log files. Done (00:00:01)

  Started deleting errand instances broker-registrar > 15b36c5c-9b70-46f1-6bd1-3856945efe32. Done (00:00:01)

Task 355 done

Started		2015-08-04 10:00:44 UTC
Finished	2015-08-04 10:01:42 UTC
Duration	00:00:58

[stdout]
CF_API_URL=https://api.10.244.0.34.xip.io
CF_SKIP_SSL_VALIDATION=true
CF_ADMIN_USERNAME=admin
BROKER_NAME=p-mysql
BROKER_URL=https://p-mysql.10.244.0.34.xip.io:443
BROKER_USERNAME=admin
Setting api endpoint to https://api.10.244.0.34.xip.io...
FAILED
Error performing request: Get https://api.10.244.0.34.xip.io/v2/info: dial tcp: i/o timeout

[stderr]
None

Errand `broker-registrar' completed with error (exit code 1)

**Comment by jinjing750629** [comment]
jjin-mac:bosh-lite jjin$ cf create-service-broker p-mysql admin password https://p-mysql.10.244.0.34.xip.io
Creating service broker p-mysql as admin...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker could not be reached: https://p-mysql.10.244.0.34.xip.io/v2/catalog

**Comment by ljfranklin** [comment]
@jinjing750629 that is strange, it seems like some of the containers in your bosh lite are having trouble talking to each other. Could you try curling from the host machine the following urls: `https://api.10.244.0.34.xip.io/v2/info` (should return some json) and `https://p-mysql.10.244.0.34.xip.io/v2/catalog` (should return Basic auth error). If that works could you try the same commands after SSHing onto the containers. To do this:
1. Run `bosh-lite/bin/add-route` from bosh-lite repo
1. `ssh vcap@10.244.7.2` (first mysql node), default password is `c1oudc0w`
1. `curl -v -k https://api.10.244.0.34.xip.io/v2/info` (if the mysql container can talk to CF, so can an errand container like broker-registrar).
1. `ssh vcap@10.244.0.134` (CF api), same password
1. `curl -v -k https://p-mysql.10.244.0.34.xip.io/v2/catalog` (this shows CF can talk to the broker)

Please give these commands a try, we can follow up once we have this info. Thanks!

**Comment by jinjing750629** [comment]
Franklin, I will have a try tomorrow and get back to you. Thanks

**Comment by jinjing750629** [comment]
Franklin, today I restarted my mac, and then used 'bosh cck' to restarted all containers. Issue disappeared. I am IT Architect in Honeywell China, located in Shanghai. My company has some conversation with Pivotal in terms of adopting CF as Honeywell's PAAS. May I know your email so that I can communicate more smoothly?

Thanks


jjin-mac:cf-mysql-release jjin$ cf marketplace
Getting services from marketplace in org honeywell / space si as admin...
OK

service   plans        description   
p-mysql   100mb, 1gb   MySQL databases on demand   

TIP:  Use 'cf marketplace -s SERVICE' to view descriptions of individual plans of a given service.

**Comment by menicosia** [comment]
Hi @jinjing750629,

We work as a team at Pivotal, so it wouldn't be best for you to e-mail any one person on the team. You'll get better response if we make sure that any member of the team can look into your problems without access to Lyle's e-mail.

Additionally, since this is an open source project, it's best if we track potential bugs where the community can see and help (ie, here on GitHub).

If you are a commercial customer of Pivotal, of course we have other ways to make sure your issues are routed to the right people, please see your account rep for more info!

In the meanwhile, if this issue has been sufficiently resolved, please feel free to close this issue. As always, you can either re-open this or create new issues when necessary. The automated gitbot process will make sure that new activity on GitHub will show up in our project management tool, [Pivotal Tracker](https://www.pivotaltracker.com/n/projects/969486).

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
