### ISSUE TITLE
acceptance-tests failed, cf start , Unauthorized error

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/cf-mysql-release#81]
Hi Expert,
My environment:
mysql v22
vsphere 5.5
ruby 2.1.6
bosh  1.3016

The deployment finished in acceptance-tests.
Error as below, could you help to check?
----------------------------------
[2015-09-09 04:03:55.72 (UTC)]> cf api https://api.192.168.2.33.xip.io --skip-ssl-validation
Setting api endpoint to https://api.192.168.2.33.xip.io...
OK

API endpoint:   https://api.192.168.2.33.xip.io (API version: 2.33.0)
Not logged in. Use 'cf login' to log in.

[2015-09-09 04:03:55.82 (UTC)]> cf auth MySQLATS-USER-1-2015_09_09-04h03m53.035s meow
API endpoint: https://api.192.168.2.33.xip.io
Authenticating...
OK
Use 'cf target' to view or set your target org and space

[2015-09-09 04:03:56.11 (UTC)]> cf target -o MySQLATS-ORG-1-2015_09_09-04h03m53.035s -s MySQLATS-SPACE-1-2015_09_09-04h03m53.035s

API endpoint:   https://api.192.168.2.33.xip.io (API version: 2.33.0)
User:           MySQLATS-USER-1-2015_09_09-04h03m53.035s
Org:            MySQLATS-ORG-1-2015_09_09-04h03m53.035s
Space:          MySQLATS-SPACE-1-2015_09_09-04h03m53.035s

[2015-09-09 04:03:56.31 (UTC)]> cf push a06314e1-c17a-4ee6-644c-dd104cd3a358 -m 256M -p ../../assets/sinatra_app -no-start
Creating app a06314e1-c17a-4ee6-644c-dd104cd3a358 in org MySQLATS-ORG-1-2015_09_09-04h03m53.035s / space MySQLATS-SPACE-1-2015_09_09-04h03m53.035s as MySQLATS-USER-1-2015_09_09-04h03m53.035s...
OK

Creating route a06314e1-c17a-4ee6-644c-dd104cd3a358.192.168.2.33.xip.io...
OK

Binding a06314e1-c17a-4ee6-644c-dd104cd3a358.192.168.2.33.xip.io to a06314e1-c17a-4ee6-644c-dd104cd3a358...
OK

Uploading a06314e1-c17a-4ee6-644c-dd104cd3a358...
Uploading app files from: ../../assets/sinatra_app
Uploading 105.8K, 12 files
Done uploading
OK

[2015-09-09 04:04:01.96 (UTC)]> cf create-service p-mysql 100mb cadc7408-e3c9-4853-7bef-e950d23c924f
Creating service cadc7408-e3c9-4853-7bef-e950d23c924f in org MySQLATS-ORG-1-2015_09_09-04h03m53.035s / space MySQLATS-SPACE-1-2015_09_09-04h03m53.035s as MySQLATS-USER-1-2015_09_09-04h03m53.035s...
OK

[2015-09-09 04:04:02.40 (UTC)]> cf bind-service a06314e1-c17a-4ee6-644c-dd104cd3a358 cadc7408-e3c9-4853-7bef-e950d23c924f
Binding service cadc7408-e3c9-4853-7bef-e950d23c924f to app a06314e1-c17a-4ee6-644c-dd104cd3a358 in org MySQLATS-ORG-1-2015_09_09-04h03m53.035s / space MySQLATS-SPACE-1-2015_09_09-04h03m53.035s as MySQLATS-USER-1-2015_09_09-04h03m53.035s...
OK
TIP: Use 'cf restage' to ensure your env variable changes take effect

[2015-09-09 04:04:02.81 (UTC)]> cf start a06314e1-c17a-4ee6-644c-dd104cd3a358
Warning: error tailing logs
Unauthorized error: You are not authorized. Error: Invalid authorization
Starting app a06314e1-c17a-4ee6-644c-dd104cd3a358 in org MySQLATS-ORG-1-2015_09_09-04h03m53.035s / space MySQLATS-SPACE-1-2015_09_09-04h03m53.035s as MySQLATS-USER-1-2015_09_09-04h03m53.035s...
FAILED
Server error, status code: 400, error code: 170001, message: Staging error: no available stagers

[2015-09-09 04:04:03.16 (UTC)]> cf logout
Logging out...
OK

**Comment by ljfranklin** [comment]
The error `Staging error: no available stagers` means your CF installation can't push an app. You could try pushing our [test app](https://github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/tree/master/assets/sinatra_app) or any other app manually to see if any apps can stage. I'd recommend opening an issue with [cf-release](https://github.com/cloudfoundry/cf-release) to get your CF installation up and running. Once you can push an app, our smoke tests should pass without error.
