### ISSUE TITLE
cf-mysql-v25 dashboard cannot login success

### ISSUE THREAD

**Issue by JackXuF** [cloudfoundry/cf-mysql-release#86]
I deploy the cf-mysql-v25 release,my cf is 222.when I create the service-broker,it return:
````````````
   Warning: This broker includes configuration for a dashboard client. Auto-creation of OAuth2 clients has been disabled in this Cloud Foundry instance. The broker catalog has been updated but its dashboard client configuration will be ignored.
Enabling access of plan 100mb-dev for service p-mysql as admin...
OK

[stderr]
None
```````````````````
    I add the client data to the  uaa's yml,but also can't login the dashboard.
    should I Manually add the client use the cf-uaac?

**Comment by aditya87** [comment]
Hello,

> I add the client data to the  uaa's yml,but also can't login the dashboard.
should I Manually add the client use the cf-uaac?  

What do you mean by this? 

Do you have the `uaa.clients.cc-service-dashboards.secret` property specified in your cf manifest?

Could you please provide us with the relevant manifest snippets around your uaa job properties from the cf manifest, making sure to remove any potentially private keys or passwords from it?

Best,
Aditya and Morgan
CF Core Services

**Comment by aditya87** [comment]
Hi, just following up, if you provide us with the information, or update us if your issue is resolved.

Thanks,
Aditya
CF Core Services

**Comment by aaronshurley** [comment]
Hi, any updates on this? Please let us know.

Thanks,
Aaron
CF Core Services

**Comment by mfine30** [comment]
Hello,

We are closing this ticket because of inactivity. If this is still a problem for you, feel free to reopen the issue. 

Best,
Morgan
CF Core Services
