### ISSUE TITLE
Create release fails, repository not found

### ISSUE THREAD

**Issue by Infra-Red** [cloudfoundry/cf-mysql-release#91]
Hi,
i'm trying to create dev releases from develop branch, i faced next issue when i run ./update:

```
Cloning into 'src/github.com/fraenkel/candiedyaml'...
Username for 'https://github.com': infra-red
Password for 'https://infra-red@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/fraenkel/candiedyaml/' not found
Clone of 'https://github.com/fraenkel/candiedyaml' into submodule path 'src/github.com/fraenkel/candiedyaml' failed
```
Looks like this repository doesnt exist anymore or maybe owner set this repo as private.

Anyone have any ideas about this?

**Comment by menicosia** [comment]
Hi @Infra-Red,

Whoa, we haven't seen anything like that before. Have you got your SSH credentials set up properly, are you able to clone a repo, etc. outside of running ./update?

-- 
  Marco Nicosia

**Comment by Infra-Red** [comment]
I can't clone this specific repository because it is no longer available (i guess this not only for me):

```
 ~ curl -I https://github.com/fraenkel/candiedyaml
HTTP/1.1 404 Not Found
```

**Comment by menicosia** [comment]
Yep, it's a bug. We'll be updating develop to a new repo ASAP.

Thanks for helping us find it!

**Comment by Infra-Red** [comment]
I see that candiedyaml submodule was deleted as unused, now i can build develop release.
Thanks for help!
