### ISSUE TITLE
I get template arbitrator not found when I "Bosh deploy"

### ISSUE THREAD

**Issue by lagask** [cloudfoundry/cf-mysql-release#94]
**whenever i run bosh deploy I get the following error.**

 Started preparing deployment > Preparing deployment. Failed: Can't find template `arbitrator' (00:00:01)

Error 190011: Can't find template `arbitrator'

Please Help

**Comment by aditya87** [comment]
Hi lagask,

Can you give us the details of how you are generating your manifest?

Thanks,
-Adi
CF Core Services

**Comment by lagask** [comment]
I use script callde generate-bosh-lite-manifest
[root@localhost cf-mysql-release]# ./scripts/generate-bosh-lite-manifest 

bosh deploy

thanx

**Comment by mfine30** [comment]
Hi Lagask,

What release are you trying to deploy? Could you please show us the output of `bosh releases`? 

Similarly, what version of `cf-mysql-release` does your manifest specify? I assume it should be `latest`. 

Thanks,
Morgan 
CF Core Services

**Comment by lagask** [comment]
it was my my mistake the release was 25 and not 26. thank you very much
