### ISSUE TITLE
When does cf-mysql-release support for Openstack?

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/cf-mysql-release#95]
I saw cf-mysql-release will be support for OpenStack. But ther
When does cf-mysql-release support for Openstack?
=============================================
shalako commented on 11 Sep 2014
Thank you for the tip! We haven't tested the MySQL release with Openstack yet; only AWS and vSphere. We will likely be prioritizing support for OpenStack later this year.

**Comment by mfine30** [comment]
Hi YunSangJun,

The cf-mysql-release should work on Openstack. Please try it and feel free to let us know if it doesn't. I'm going to close out this issue. 

If you still have a problem, please reopen this issue.

Best,
Morgan 
CF Core Services

**Comment by YunSangJun** [comment]
Hi. Morgan.

There is no iaas-settings.yml for openstack on guide doc.

Deploy on AWS or vSphere
$ cp cf-mysql-release/manifest-generation/examples/aws/iaas-settings.yml \
    cf-mysql-release/manifest-generation/examples/property-overrides.yml \
    cf-mysql-release/manifest-generation/examples/cf-stub.yml \
    <YOUR_CONFIG_REPO>/cf-mysql/

Thank you.

**Comment by aditya87** [comment]
Hi YunSangJun,

We don't provide an explicit stub for OpenStack, but you can use our vSphere iaas-settings stubs as a template to create your own iaas-settings stub for OpenStack. The main components of an iaas-settings stub are:

1. Names of subnets under global properties
1. Subnet configs
1. Stemcell information
1. Compilation cloud properties
1. Resource Pool Cloud properties
1. Disk pools

There may be some structural changes for OpenStack underneath this general skeleton. Please refer to https://bosh.io/docs/openstack-cpi.html#networks

Let us know if you have any more questions. Thanks!

-Adi
CF Core Services

**Comment by YunSangJun** [comment]
Hi. there.

Finally, i succeeded to deploy cf-mysql-release on Openstack.

So, i share my iaas-settings.yml for Openstack(kilo ver).
```
properties:

iaas_settings:
  <<: (( merge || nil ))

# NOTE:
# Replace 10.0.{0,1,2} part of the octet
# with your network configuration
  subnet_configs:
  - name: mysql1
    subnets:
    - range: 10.0.0.0/24                  
      gateway: 10.0.0.1  
      reserved:
      - 10.0.0.2-10.0.0.109
      - 10.0.0.130-10.0.0.254
      static:
      - 10.0.0.120-10.0.0.124
      dns:
      - 8.8.8.8
      cloud_properties:
        net_id: 9914f1b5-e739-4b06-9013-8d7d19a5b16e  # network id for mysql
        security_groups:  # security group for mysql
        - cf 

  - name: mysql2
    subnets:
    - range: 10.0.1.0/24
      gateway: 10.0.1.1
      reserved:
      - 10.0.1.2-10.0.1.109
      - 10.0.1.130-10.0.1.254
      static:
        - 10.0.1.120-10.0.1.124
      dns:
      - 8.8.8.8
      cloud_properties:                      
        net_id: 9914f1b5-e739-4b06-9013-8d7d19a5b16e  
        security_groups:
        - cf 

  - name: mysql3
    subnets:
    - range: 10.0.2.0/24
      gateway: 10.0.2.1
      reserved:
      - 10.0.2.2-10.0.2.109
      - 10.0.2.130-10.0.2.254
      static:
        - 10.0.2.120-10.0.2.124
      dns:
      - 8.8.8.8
      cloud_properties:                           
        net_id: 9914f1b5-e739-4b06-9013-8d7d19a5b16e  
        security_groups:
        - cf 

  stemcell: &stemcell
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
    
  compilation_cloud_properties:
    instance_type: m1.small  

  resource_pool_cloud_properties:
  - name: mysql_z1
    cloud_properties:
      instance_type: m1.small

  - name: mysql_z2
    cloud_properties:
      instance_type: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.instance_type ))

  - name: mysql_z3
    cloud_properties:
      instance_type: (( iaas_settings.resource_pool_cloud_properties.mysql_z1.cloud_properties.instance_type ))

  - name: arbitrator_z3
    cloud_properties: 
      instance_type: m1.small

  - name: proxy_z1
    cloud_properties:
      instance_type: m1.small

  - name: proxy_z2
    cloud_properties:
      instance_type: (( iaas_settings.resource_pool_cloud_properties.proxy_z1.cloud_properties.instance_type ))

  - name: cf-mysql-broker_z1
    cloud_properties:
      instance_type: m1.small

  - name: cf-mysql-broker_z2
    cloud_properties:
      instance_type: (( iaas_settings.resource_pool_cloud_properties.cf-mysql-broker_z1.cloud_properties.instance_type ))

  - name: errands_z1
    cloud_properties:
      instance_type: m1.small

  disk_pools:
  - name: mysql-persistent-disk
    disk_size: 8196               # your deployment will fail if this is less than 3GB
```
Then why don't you provide iaas-settings.yml for Openstack only?. Is there any reason?.
